# -*- coding: utf-8 -*-
# ------------------------------
# @Time    : 2021/10/20 9:09
# @Author  : lisl3
# @File    : b_share_field.py
# @Project : cscfist
# @Function: 中国B股
# @Version : V0.0.1
# ------------------------------
from sqlalchemy import Column, VARCHAR, Numeric
from sqlalchemy.ext.declarative import declarative_base

Base = declarative_base()


class BSHAREADMPERMITSCHEDULE(Base):
    """中国B股行政许可事项进度表"""
    __tablename__ = 'BSHAREADMPERMITSCHEDULE'
    OBJECT_ID = Column(VARCHAR(38), primary_key=True, comment='对象ID')
    COMP_ID = Column(VARCHAR(10), comment='公司ID')
    ANNDATE = Column(VARCHAR(8), comment='公告日期')
    ENDDATE = Column(VARCHAR(8), comment='截止日期')
    TYPE_NAME = Column(VARCHAR(300), comment='申请事项')
    TYPE_CODE = Column(Numeric(9, 0), comment='审核类型代码')
    APPLY_PICKUP_DATE = Column(VARCHAR(8), comment='申请材料接收日')
    NOTICE_CORRECTION_DATE = Column(VARCHAR(8), comment='通知补正日')
    RECEIVE_CORRECTION_MATERIAL = Column(VARCHAR(8), comment='接收补正材料日')
    ADMISSIBILITY_DATE = Column(VARCHAR(8), comment='受理决定日')
    NO_ADMISSIBILITY_DATE = Column(VARCHAR(8), comment='不予受理决定日')
    FEEDBACK_DATE1 = Column(VARCHAR(8), comment='第一次反馈意见日')
    RECEIVE_FEEDBACK_DATE1 = Column(VARCHAR(8), comment='接收第一次反馈材料日')
    FEEDBACK_DATE2 = Column(VARCHAR(8), comment='第二次反馈意见日')
    RECEIVE_FEEDBACK_DATE2 = Column(VARCHAR(8), comment='接收第二次反馈材料日')
    REVIEW_DATE = Column(VARCHAR(8), comment='审查决定日')
    MEMO = Column(VARCHAR(1000), comment='说明')
    COMP_NAME = Column(VARCHAR(300), comment='申请人名称')
    PROGRESS_CODE = Column(Numeric(9, 0), comment='审核进度代码')
    ANN_DATE_NDRC = Column(VARCHAR(8), comment='审结日期')
    AUDIT_EVENT_ID = Column(VARCHAR(40), comment='审核事件ID')
    AUDIT_CHANNEL_CODE = Column(Numeric(9, 0), comment='审核通道代码')
    FEEDBACK_DATE = Column(VARCHAR(8), comment='反馈回复日期')
    OTHER_COMP_ID = Column(VARCHAR(10), comment='其他公司ID')
    OTHER_COMP_TYPE_CODE = Column(Numeric(9, 0), comment='其他公司类型代码')


class BSHAREAGENCY(Base):
    """中国B股发行中介机构"""
    __tablename__ = 'BSHAREAGENCY'
    OBJECT_ID = Column(VARCHAR(100), primary_key=True, comment='对象ID')
    S_INFO_WINDCODE = Column(VARCHAR(40), comment='Wind代码')
    S_AGENCY_NAME = Column(VARCHAR(200), comment='机构名称')
    S_RELATION_TYPCODE = Column(VARCHAR(10), comment='关系类型代码')
    S_BUSINESS_TYPCODE = Column(Numeric(9, 0), comment='业务类型代码')
    S_AGENCY_NAMEID = Column(VARCHAR(200), comment='机构名称ID')
    BEGINDATE = Column(VARCHAR(8), comment='起始日期')
    ENDDATE = Column(VARCHAR(8), comment='截止日期')
    SEQUENCE1 = Column(VARCHAR(6), comment='序号')
    ANN_DATE = Column(VARCHAR(8), comment='公告日期')


class BSHAREAUDITOPINION(Base):
    """中国B股审计意见"""
    __tablename__ = 'BSHAREAUDITOPINION'
    OBJECT_ID = Column(VARCHAR(100), primary_key=True, comment='对象ID')
    S_INFO_WINDCODE = Column(VARCHAR(40), comment='Wind代码')
    ANN_DT = Column(VARCHAR(8), comment='公告日期')
    REPORT_PERIOD = Column(VARCHAR(8), comment='报告期')
    S_STMNOTE_AUDIT_CATEGORY = Column(Numeric(9, 0), comment='审计结果类别代码')
    S_STMNOTE_AUDIT_AGENCY = Column(VARCHAR(100), comment='会计师事务所')
    S_STMNOTE_AUDIT_CPA = Column(VARCHAR(100), comment='签字会计师')


class BSHAREBALANCESHEET(Base):
    """中国B股资产负债表"""
    __tablename__ = 'BSHAREBALANCESHEET'
    OBJECT_ID = Column(VARCHAR(100), primary_key=True, comment='对象ID')
    S_INFO_WINDCODE = Column(VARCHAR(40), comment='Wind代码')
    WIND_CODE = Column(VARCHAR(40), comment='Wind代码')
    ANN_DT = Column(VARCHAR(8), comment='公告日期')
    REPORT_PERIOD = Column(VARCHAR(8), comment='报告期')
    STATEMENT_TYPE = Column(VARCHAR(10), comment='报表类型')
    CRNCY_CODE = Column(VARCHAR(10), comment='货币代码')
    MONETARY_CAP = Column(Numeric(20, 4), comment='货币资金')
    TRADABLE_FIN_ASSETS = Column(Numeric(20, 4), comment='交易性金融资产')
    NOTES_RCV = Column(Numeric(20, 4), comment='应收票据')
    ACCT_RCV = Column(Numeric(20, 4), comment='应收账款')
    OTH_RCV = Column(Numeric(20, 4), comment='其他应收款')
    PREPAY = Column(Numeric(20, 4), comment='预付款项')
    DVD_RCV = Column(Numeric(20, 4), comment='应收股利')
    INT_RCV = Column(Numeric(20, 4), comment='应收利息')
    INVENTORIES = Column(Numeric(20, 4), comment='存货')
    CONSUMPTIVE_BIO_ASSETS = Column(Numeric(20, 4), comment='消耗性生物资产')
    DEFERRED_EXP = Column(Numeric(20, 4), comment='待摊费用')
    NON_CUR_ASSETS_DUE_WITHIN_1Y = Column(Numeric(20, 4), comment='一年内到期的非流动资产')
    SETTLE_RSRV = Column(Numeric(20, 4), comment='结算备付金')
    LOANS_TO_OTH_BANKS = Column(Numeric(20, 4), comment='拆出资金')
    PREM_RCV = Column(Numeric(20, 4), comment='应收保费')
    RCV_FROM_REINSURER = Column(Numeric(20, 4), comment='应收分保账款')
    RCV_FROM_CEDED_INSUR_CONT_RSRV = Column(Numeric(20, 4), comment='应收分保合同准备金')
    RED_MONETARY_CAP_FOR_SALE = Column(Numeric(20, 4), comment='买入返售金融资产')
    OTH_CUR_ASSETS = Column(Numeric(20, 4), comment='其他流动资产')
    TOT_CUR_ASSETS = Column(Numeric(20, 4), comment='流动资产合计')
    FIN_ASSETS_AVAIL_FOR_SALE = Column(Numeric(20, 4), comment='可供出售金融资产')
    HELD_TO_MTY_INVEST = Column(Numeric(20, 4), comment='持有至到期投资')
    LONG_TERM_EQY_INVEST = Column(Numeric(20, 4), comment='长期股权投资')
    INVEST_REAL_ESTATE = Column(Numeric(20, 4), comment='投资性房地产')
    TIME_DEPOSITS = Column(Numeric(20, 4), comment='定期存款')
    OTH_ASSETS = Column(Numeric(20, 4), comment='其他资产')
    LONG_TERM_REC = Column(Numeric(20, 4), comment='长期应收款')
    FIX_ASSETS = Column(Numeric(20, 4), comment='固定资产')
    CONST_IN_PROG = Column(Numeric(20, 4), comment='在建工程')
    PROJ_MATL = Column(Numeric(20, 4), comment='工程物资')
    FIX_ASSETS_DISP = Column(Numeric(20, 4), comment='固定资产清理')
    PRODUCTIVE_BIO_ASSETS = Column(Numeric(20, 4), comment='生产性生物资产')
    OIL_AND_NATURAL_GAS_ASSETS = Column(Numeric(20, 4), comment='油气资产')
    INTANG_ASSETS = Column(Numeric(20, 4), comment='无形资产')
    R_AND_D_COSTS = Column(Numeric(20, 4), comment='开发支出')
    GOODWILL = Column(Numeric(20, 4), comment='商誉')
    LONG_TERM_DEFERRED_EXP = Column(Numeric(20, 4), comment='长期待摊费用')
    DEFERRED_TAX_ASSETS = Column(Numeric(20, 4), comment='递延所得税资产')
    LOANS_AND_ADV_GRANTED = Column(Numeric(20, 4), comment='发放贷款及垫款')
    OTH_NON_CUR_ASSETS = Column(Numeric(20, 4), comment='其他非流动资产')
    TOT_NON_CUR_ASSETS = Column(Numeric(20, 4), comment='非流动资产合计')
    CASH_DEPOSITS_CENTRAL_BANK = Column(Numeric(20, 4), comment='现金及存放中央银行款项')
    ASSET_DEP_OTH_BANKS_FIN_INST = Column(Numeric(20, 4), comment='存放同业和其它金融机构款项')
    PRECIOUS_METALS = Column(Numeric(20, 4), comment='贵金属')
    DERIVATIVE_FIN_ASSETS = Column(Numeric(20, 4), comment='衍生金融资产')
    AGENCY_BUS_ASSETS = Column(Numeric(20, 4), comment='代理业务资产')
    SUBR_REC = Column(Numeric(20, 4), comment='应收代位追偿款')
    RCV_CEDED_UNEARNED_PREM_RSRV = Column(Numeric(20, 4), comment='应收分保未到期责任准备金')
    RCV_CEDED_CLAIM_RSRV = Column(Numeric(20, 4), comment='应收分保未决赔款准备金')
    RCV_CEDED_LIFE_INSUR_RSRV = Column(Numeric(20, 4), comment='应收分保寿险责任准备金')
    RCV_CEDED_LT_HEALTH_INSUR_RSRV = Column(Numeric(20, 4), comment='应收分保长期健康险责任准备金')
    MRGN_PAID = Column(Numeric(20, 4), comment='存出保证金')
    INSURED_PLEDGE_LOAN = Column(Numeric(20, 4), comment='保户质押贷款')
    CAP_MRGN_PAID = Column(Numeric(20, 4), comment='存出资本保证金')
    INDEPENDENT_ACCT_ASSETS = Column(Numeric(20, 4), comment='独立账户资产')
    CLIENTS_CAP_DEPOSIT = Column(Numeric(20, 4), comment='客户资金存款')
    CLIENTS_RSRV_SETTLE = Column(Numeric(20, 4), comment='客户备付金')
    INCL_SEAT_FEES_EXCHANGE = Column(Numeric(20, 4), comment='其中:交易席位费')
    RCV_INVEST = Column(Numeric(20, 4), comment='应收款项类投资')
    TOT_ASSETS = Column(Numeric(20, 4), comment='资产总计')
    ST_BORROW = Column(Numeric(20, 4), comment='短期借款')
    BORROW_CENTRAL_BANK = Column(Numeric(20, 4), comment='向中央银行借款')
    DEPOSIT_RECEIVED_IB_DEPOSITS = Column(Numeric(20, 4), comment='吸收存款及同业存放')
    LOANS_OTH_BANKS = Column(Numeric(20, 4), comment='拆入资金')
    TRADABLE_FIN_LIAB = Column(Numeric(20, 4), comment='交易性金融负债')
    NOTES_PAYABLE = Column(Numeric(20, 4), comment='应付票据')
    ACCT_PAYABLE = Column(Numeric(20, 4), comment='应付账款')
    ADV_FROM_CUST = Column(Numeric(20, 4), comment='预收款项')
    FUND_SALES_FIN_ASSETS_RP = Column(Numeric(20, 4), comment='卖出回购金融资产款')
    HANDLING_CHARGES_COMM_PAYABLE = Column(Numeric(20, 4), comment='应付手续费及佣金')
    EMPL_BEN_PAYABLE = Column(Numeric(20, 4), comment='应付职工薪酬')
    TAXES_SURCHARGES_PAYABLE = Column(Numeric(20, 4), comment='应交税费')
    INT_PAYABLE = Column(Numeric(20, 4), comment='应付利息')
    DVD_PAYABLE = Column(Numeric(20, 4), comment='应付股利')
    OTH_PAYABLE = Column(Numeric(20, 4), comment='其他应付款')
    ACC_EXP = Column(Numeric(20, 4), comment='预提费用')
    DEFERRED_INC = Column(Numeric(20, 4), comment='递延收益')
    ST_BONDS_PAYABLE = Column(Numeric(20, 4), comment='应付短期债券')
    PAYABLE_TO_REINSURER = Column(Numeric(20, 4), comment='应付分保账款')
    RSRV_INSUR_CONT = Column(Numeric(20, 4), comment='保险合同准备金')
    ACTING_TRADING_SEC = Column(Numeric(20, 4), comment='代理买卖证券款')
    ACTING_UW_SEC = Column(Numeric(20, 4), comment='代理承销证券款')
    NON_CUR_LIAB_DUE_WITHIN_1Y = Column(Numeric(20, 4), comment='一年内到期的非流动负债')
    OTH_CUR_LIAB = Column(Numeric(20, 4), comment='其他流动负债')
    TOT_CUR_LIAB = Column(Numeric(20, 4), comment='流动负债合计')
    LT_BORROW = Column(Numeric(20, 4), comment='长期借款')
    BONDS_PAYABLE = Column(Numeric(20, 4), comment='应付债券')
    LT_PAYABLE = Column(Numeric(20, 4), comment='长期应付款')
    SPECIFIC_ITEM_PAYABLE = Column(Numeric(20, 4), comment='专项应付款')
    PROVISIONS = Column(Numeric(20, 4), comment='预计负债')
    DEFERRED_TAX_LIAB = Column(Numeric(20, 4), comment='递延所得税负债')
    DEFERRED_INC_NON_CUR_LIAB = Column(Numeric(20, 4), comment='递延收益-非流动负债')
    OTH_NON_CUR_LIAB = Column(Numeric(20, 4), comment='其他非流动负债')
    TOT_NON_CUR_LIAB = Column(Numeric(20, 4), comment='非流动负债合计')
    LIAB_DEP_OTH_BANKS_FIN_INST = Column(Numeric(20, 4), comment='同业和其它金融机构存放款项')
    DERIVATIVE_FIN_LIAB = Column(Numeric(20, 4), comment='衍生金融负债')
    CUST_BANK_DEP = Column(Numeric(20, 4), comment='吸收存款')
    AGENCY_BUS_LIAB = Column(Numeric(20, 4), comment='代理业务负债')
    OTH_LIAB = Column(Numeric(20, 4), comment='其他负债')
    PREM_RECEIVED_ADV = Column(Numeric(20, 4), comment='预收保费')
    DEPOSIT_RECEIVED = Column(Numeric(20, 4), comment='存入保证金')
    INSURED_DEPOSIT_INVEST = Column(Numeric(20, 4), comment='保户储金及投资款')
    UNEARNED_PREM_RSRV = Column(Numeric(20, 4), comment='未到期责任准备金')
    OUT_LOSS_RSRV = Column(Numeric(20, 4), comment='未决赔款准备金')
    LIFE_INSUR_RSRV = Column(Numeric(20, 4), comment='寿险责任准备金')
    LT_HEALTH_INSUR_V = Column(Numeric(20, 4), comment='长期健康险责任准备金')
    INDEPENDENT_ACCT_LIAB = Column(Numeric(20, 4), comment='独立账户负债')
    INCL_PLEDGE_LOAN = Column(Numeric(20, 4), comment='其中:质押借款')
    CLAIMS_PAYABLE = Column(Numeric(20, 4), comment='应付赔付款')
    DVD_PAYABLE_INSURED = Column(Numeric(20, 4), comment='应付保单红利')
    TOT_LIAB = Column(Numeric(20, 4), comment='负债合计')
    CAP_STK = Column(Numeric(20, 4), comment='股本')
    CAP_RSRV = Column(Numeric(20, 4), comment='资本公积金')
    SPECIAL_RSRV = Column(Numeric(20, 4), comment='专项储备')
    SURPLUS_RSRV = Column(Numeric(20, 4), comment='盈余公积金')
    UNDISTRIBUTED_PROFIT = Column(Numeric(20, 4), comment='未分配利润')
    LESS_TSY_STK = Column(Numeric(20, 4), comment='减:库存股')
    PROV_NOM_RISKS = Column(Numeric(20, 4), comment='一般风险准备')
    CNVD_DIFF_FOREIGN_CURR_STAT = Column(Numeric(20, 4), comment='外币报表折算差额')
    UNCONFIRMED_INVEST_LOSS = Column(Numeric(20, 4), comment='未确认的投资损失')
    MINORITY_INT = Column(Numeric(20, 4), comment='少数股东权益')
    TOT_SHRHLDR_EQY_EXCL_MIN_INT = Column(Numeric(20, 4), comment='股东权益合计(不含少数股东权益)')
    TOT_SHRHLDR_EQY_INCL_MIN_INT = Column(Numeric(20, 4), comment='股东权益合计(含少数股东权益)')
    TOT_LIAB_SHRHLDR_EQY = Column(Numeric(20, 4), comment='负债及股东权益总计')
    COMP_TYPE_CODE = Column(VARCHAR(2), comment='公司类型代码')


class BSHARECAPITALIZATION(Base):
    """中国B股股本"""
    __tablename__ = 'BSHARECAPITALIZATION'
    OBJECT_ID = Column(VARCHAR(100), primary_key=True, comment='对象ID')
    WIND_CODE = Column(VARCHAR(40), comment='Wind代码')
    S_INFO_WINDCODE = Column(VARCHAR(40), comment='Wind代码')
    CHANGE_DT = Column(VARCHAR(8), comment='变动日期')
    TOT_SHR = Column(Numeric(20, 4), comment='总股本')
    FLOAT_SHR = Column(Numeric(20, 4), comment='流通股(万股)')
    FLOAT_A_SHR = Column(Numeric(20, 4), comment='流通A股(万股)')
    FLOAT_B_SHR = Column(Numeric(20, 4), comment='流通B股(万股)')
    FLOAT_H_SHR = Column(Numeric(20, 4), comment='流通H股(万股)')
    FLOAT_OVERSEAS_SHR = Column(Numeric(20, 4), comment='境外流通股(万股)')
    RESTRICTED_A_SHR = Column(Numeric(20, 4), comment='限售A股(万股)')
    S_SHARE_RTD_STATE = Column(Numeric(20, 4), comment='限售A股(国家持股)')
    S_SHARE_RTD_STATEJUR = Column(Numeric(20, 4), comment='限售A股(国有法人持股)')
    S_SHARE_RTD_SUBOTHERDOMES = Column(Numeric(20, 4), comment='限售A股(其他内资持股)')
    S_SHARE_RTD_DOMESJUR = Column(Numeric(20, 4), comment='限售A股(其他内资持股:境内法人持股)')
    S_SHARE_RTD_INST = Column(Numeric(20, 4), comment='限售A股(其他内资持股:机构配售股)')
    S_SHARE_RTD_DOMESNP = Column(Numeric(20, 4), comment='限售A股(其他内资持股:境内自然人持股)')
    S_SHARE_RTD_SENMANAGER = Column(Numeric(20, 4), comment='限售股份(高管持股)(万股)')
    S_SHARE_RTD_SUBFRGN = Column(Numeric(20, 4), comment='限售A股(外资持股)')
    S_SHARE_RTD_FRGNJUR = Column(Numeric(20, 4), comment='限售A股(境外法人持股)')
    S_SHARE_RTD_FRGNNP = Column(Numeric(20, 4), comment='限售A股(境外自然人持股)')
    RESTRICTED_B_SHR = Column(Numeric(20, 4), comment='限售B股')
    OTHER_RESTRICTED_SHR = Column(Numeric(20, 4), comment='其他限售股')
    NON_TRADABLE_SHR = Column(Numeric(20, 4), comment='非流通股')
    S_SHARE_NTRD_STATE_PCT = Column(Numeric(20, 4), comment='非流通股(国有股)')
    S_SHARE_NTRD_STATE = Column(Numeric(20, 4), comment='非流通股(国家股)')
    S_SHARE_NTRD_STATJUR = Column(Numeric(20, 4), comment='非流通股(国有法人股)')
    S_SHARE_NTRD_SUBDOMESJUR = Column(Numeric(20, 4), comment='非流通股(境内法人股)')
    S_SHARE_NTRD_DOMESINITOR = Column(Numeric(20, 4), comment='非流通股(境内法人股:境内发起人股)')
    S_SHARE_NTRD_IPOJURIS = Column(Numeric(20, 4), comment='非流通股(境内法人股:募集法人股)')
    S_SHARE_NTRD_GENJURIS = Column(Numeric(20, 4), comment='非流通股(境内法人股:一般法人股)')
    S_SHARE_NTRD_STRTINVESTOR = Column(Numeric(20, 4), comment='非流通股(境内法人股:战略投资者持股)')
    S_SHARE_NTRD_FUNDBAL = Column(Numeric(20, 4), comment='非流通股(境内法人股:基金持股)')
    S_SHARE_NTRD_IPOINIP = Column(Numeric(20, 4), comment='非流通股(自然人股)')
    S_SHARE_NTRD_TRFNSHARE = Column(Numeric(20, 4), comment='转配股(万股)')
    S_SHARE_NTRD_SNORMNGER = Column(Numeric(20, 4), comment='流通股(高管持股)')
    S_SHARE_NTRD_INSDEREMP = Column(Numeric(20, 4), comment='内部职工股(万股)')
    S_SHARE_NTRD_PRFSHARE = Column(Numeric(20, 4), comment='优先股(万股)')
    S_SHARE_NTRD_NONLSTFRGN = Column(Numeric(20, 4), comment='非流通股(非上市外资股)')
    S_SHARE_NTRD_STAQ = Column(Numeric(20, 4), comment='STAQ股(万股)')
    S_SHARE_NTRD_NET = Column(Numeric(20, 4), comment='NET股(万股)')
    S_SHARE_CHANGEREASON = Column(VARCHAR(30), comment='股本变动原因')


class BSHARECASHFLOW(Base):
    """中国B股现金流量表"""
    __tablename__ = 'BSHARECASHFLOW'
    OBJECT_ID = Column(VARCHAR(100), primary_key=True, comment='对象ID')
    S_INFO_WINDCODE = Column(VARCHAR(40), comment='Wind代码')
    WIND_CODE = Column(VARCHAR(40), comment='Wind代码')
    ANN_DT = Column(VARCHAR(8), comment='公告日期')
    REPORT_PERIOD = Column(VARCHAR(8), comment='报告期')
    STATEMENT_TYPE = Column(VARCHAR(10), comment='报表类型')
    CRNCY_CODE = Column(VARCHAR(10), comment='货币代码')
    CASH_RECP_SG_AND_RS = Column(Numeric(20, 4), comment='销售商品、提供劳务收到的现金')
    RECP_TAX_RENDS = Column(Numeric(20, 4), comment='收到的税费返还')
    NET_INCR_DEP_COB = Column(Numeric(20, 4), comment='客户存款和同业存放款项净增加额')
    NET_INCR_LOANS_CENTRAL_BANK = Column(Numeric(20, 4), comment='向中央银行借款净增加额')
    NET_INCR_FUND_BORR_OFI = Column(Numeric(20, 4), comment='向其他金融机构拆入资金净增加额')
    CASH_RECP_PREM_ORIG_INCO = Column(Numeric(20, 4), comment='收到原保险合同保费取得的现金')
    NET_INCR_INSURED_DEP = Column(Numeric(20, 4), comment='保户储金净增加额')
    NET_CASH_RECEIVED_REINSU_BUS = Column(Numeric(20, 4), comment='收到再保业务现金净额')
    NET_INCR_DISP_TFA = Column(Numeric(20, 4), comment='处置交易性金融资产净增加额')
    NET_INCR_INT_HANDLING_CHRG = Column(Numeric(20, 4), comment='收取利息和手续费净增加额')
    NET_INCR_DISP_FAAS = Column(Numeric(20, 4), comment='处置可供出售金融资产净增加额')
    NET_INCR_LOANS_OTHER_BANK = Column(Numeric(20, 4), comment='拆入资金净增加额')
    NET_INCR_REPURCH_BUS_FUND = Column(Numeric(20, 4), comment='回购业务资金净增加额')
    OTHER_CASH_RECP_RAL_OPER_ACT = Column(Numeric(20, 4), comment='收到其他与经营活动有关的现金')
    STOT_CASH_INFLOWS_OPER_ACT = Column(Numeric(20, 4), comment='经营活动现金流入小计')
    CASH_PAY_GOODS_PURCH_SERV_REC = Column(Numeric(20, 4), comment='购买商品、接受劳务支付的现金')
    CASH_PAY_BEH_EMPL = Column(Numeric(20, 4), comment='支付给职工以及为职工支付的现金')
    PAY_ALL_TYP_TAX = Column(Numeric(20, 4), comment='支付的各项税费')
    NET_INCR_CLIENTS_LOAN_ADV = Column(Numeric(20, 4), comment='客户贷款及垫款净增加额')
    NET_INCR_DEP_CBOB = Column(Numeric(20, 4), comment='存放央行和同业款项净增加额')
    CASH_PAY_CLAIMS_ORIG_INCO = Column(Numeric(20, 4), comment='支付原保险合同赔付款项的现金')
    HANDLING_CHRG_PAID = Column(Numeric(20, 4), comment='支付手续费的现金')
    COMM_INSUR_PLCY_PAID = Column(Numeric(20, 4), comment='支付保单红利的现金')
    OTHER_CASH_PAY_RAL_OPER_ACT = Column(Numeric(20, 4), comment='支付其他与经营活动有关的现金')
    STOT_CASH_OUTFLOWS_OPER_ACT = Column(Numeric(20, 4), comment='经营活动现金流出小计')
    NET_CASH_FLOWS_OPER_ACT = Column(Numeric(20, 4), comment='经营活动产生的现金流量净额')
    CASH_RECP_DISP_WITHDRWL_INVEST = Column(Numeric(20, 4), comment='收回投资收到的现金')
    CASH_RECP_RETURN_INVEST = Column(Numeric(20, 4), comment='取得投资收益收到的现金')
    NET_CASH_RECP_DISP_FIOLTA = Column(Numeric(20, 4), comment='处置固定资产、无形资产和其他长期资产收回的现金净额')
    NET_CASH_RECP_DISP_SOBU = Column(Numeric(20, 4), comment='处置子公司及其他营业单位收到的现金净额')
    OTHER_CASH_RECP_RAL_INV_ACT = Column(Numeric(20, 4), comment='收到其他与投资活动有关的现金')
    STOT_CASH_INFLOWS_INV_ACT = Column(Numeric(20, 4), comment='投资活动现金流入小计')
    CASH_PAY_ACQ_CONST_FIOLTA = Column(Numeric(20, 4), comment='购建固定资产、无形资产和其他长期资产支付的现金')
    CASH_PAID_INVEST = Column(Numeric(20, 4), comment='投资支付的现金')
    NET_CASH_PAY_AQUIS_SOBU = Column(Numeric(20, 4), comment='取得子公司及其他营业单位支付的现金净额')
    OTHER_CASH_PAY_RAL_INV_ACT = Column(Numeric(20, 4), comment='支付其他与投资活动有关的现金')
    NET_INCR_PLEDGE_LOAN = Column(Numeric(20, 4), comment='质押贷款净增加额')
    STOT_CASH_OUTFLOWS_INV_ACT = Column(Numeric(20, 4), comment='投资活动现金流出小计')
    NET_CASH_FLOWS_INV_ACT = Column(Numeric(20, 4), comment='投资活动产生的现金流量净额')
    CASH_RECP_CAP_CONTRIB = Column(Numeric(20, 4), comment='吸收投资收到的现金')
    INCL_CASH_REC_SAIMS = Column(Numeric(20, 4), comment='其中:子公司吸收少数股东投资收到的现金')
    CASH_RECP_BORROW = Column(Numeric(20, 4), comment='取得借款收到的现金')
    PROC_ISSUE_BONDS = Column(Numeric(20, 4), comment='发行债券收到的现金')
    OTHER_CASH_RECP_RAL_FNC_ACT = Column(Numeric(20, 4), comment='收到其他与筹资活动有关的现金')
    STOT_CASH_INFLOWS_FNC_ACT = Column(Numeric(20, 4), comment='筹资活动现金流入小计')
    CASH_PREPAY_AMT_BORR = Column(Numeric(20, 4), comment='偿还债务支付的现金')
    CASH_PAY_DIST_DPCP_INT_EXP = Column(Numeric(20, 4), comment='分配股利、利润或偿付利息支付的现金')
    INCL_DVD_PROFIT_PAID_SC_MS = Column(Numeric(20, 4), comment='其中:子公司支付给少数股东的股利、利润')
    OTHER_CASH_PAY_RAL_FNC_ACT = Column(Numeric(20, 4), comment='支付其他与筹资活动有关的现金')
    STOT_CASH_OUTFLOWS_FNC_ACT = Column(Numeric(20, 4), comment='筹资活动现金流出小计')
    NET_CASH_FLOWS_FNC_ACT = Column(Numeric(20, 4), comment='筹资活动产生的现金流量净额')
    EFF_FX_FLU_CASH = Column(Numeric(20, 4), comment='汇率变动对现金的影响')
    NET_INCR_CASH_CASH_EQU = Column(Numeric(20, 4), comment='现金及现金等价物净增加额')
    CASH_CASH_EQU_BEG_PERIOD = Column(Numeric(20, 4), comment='期初现金及现金等价物余额')
    CASH_CASH_EQU_END_PERIOD = Column(Numeric(20, 4), comment='期末现金及现金等价物余额')
    NET_PROFIT = Column(Numeric(20, 4), comment='净利润')
    UNCONFIRMED_INVEST_LOSS = Column(Numeric(20, 4), comment='未确认投资损失')
    PLUS_PROV_DEPR_ASSETS = Column(Numeric(20, 4), comment='加:资产减值准备')
    DEPR_FA_COGA_DPBA = Column(Numeric(20, 4), comment='固定资产折旧、油气资产折耗、生产性生物资产折旧')
    AMORT_INTANG_ASSETS = Column(Numeric(20, 4), comment='无形资产摊销')
    AMORT_LT_DEFERRED_EXP = Column(Numeric(20, 4), comment='长期待摊费用摊销')
    DECR_DEFERRED_EXP = Column(Numeric(20, 4), comment='待摊费用减少')
    INCR_ACC_EXP = Column(Numeric(20, 4), comment='预提费用增加')
    LOSS_DISP_FIOLTA = Column(Numeric(20, 4), comment='处置固定、无形资产和其他长期资产的损失')
    LOSS_SCR_FA = Column(Numeric(20, 4), comment='固定资产报废损失')
    LOSS_FV_CHG = Column(Numeric(20, 4), comment='公允价值变动损失')
    FIN_EXP = Column(Numeric(20, 4), comment='财务费用')
    INVEST_LOSS = Column(Numeric(20, 4), comment='投资损失')
    DECR_DEFERRED_INC_TAX_ASSETS = Column(Numeric(20, 4), comment='递延所得税资产减少')
    INCR_DEFERRED_INC_TAX_LIAB = Column(Numeric(20, 4), comment='递延所得税负债增加')
    DECR_INVENTORIES = Column(Numeric(20, 4), comment='存货的减少')
    DECR_OPER_PAYABLE = Column(Numeric(20, 4), comment='经营性应收项目的减少')
    INCR_OPER_PAYABLE = Column(Numeric(20, 4), comment='经营性应付项目的增加')
    OTHERS = Column(Numeric(20, 4), comment='其他')
    IM_NET_CASH_FLOWS_OPER_ACT = Column(Numeric(20, 4), comment='间接法-经营活动产生的现金流量净额')
    CONV_DEBT_INTO_CAP = Column(Numeric(20, 4), comment='债务转为资本')
    CONV_CORP_BONDS_DUE_WITHIN_1Y = Column(Numeric(20, 4), comment='一年内到期的可转换公司债券')
    FA_FNC_LEASES = Column(Numeric(20, 4), comment='融资租入固定资产')
    END_BAL_CASH = Column(Numeric(20, 4), comment='现金的期末余额')
    LESS_BEG_BAL_CASH = Column(Numeric(20, 4), comment='减:现金的期初余额')
    PLUS_END_BAL_CASH_EQU = Column(Numeric(20, 4), comment='加:现金等价物的期末余额')
    LESS_BEG_BAL_CASH_EQU = Column(Numeric(20, 4), comment='减:现金等价物的期初余额')
    IM_NET_INCR_CASH_CASH_EQU = Column(Numeric(20, 4), comment='间接法-现金及现金等价物净增加额')
    FREE_CASH_FLOW = Column(Numeric(20, 4), comment='企业自由现金流量(FCFF)')
    COMP_TYPE_CODE = Column(VARCHAR(2), comment='公司类型代码')


class BSHARECOCAPITALOPERATION(Base):
    """中国B股公司资本运作"""
    __tablename__ = 'BSHARECOCAPITALOPERATION'
    OBJECT_ID = Column(VARCHAR(38), primary_key=True, comment='对象ID')
    S_INFO_COMPCODE = Column(VARCHAR(10), comment='公司ID')
    S_EVENT_ID = Column(VARCHAR(40), comment='事件ID')
    S_EVENT_CATEGORYCODE = Column(Numeric(9, 0), comment='事件类型代码')
    ANN_DATE = Column(VARCHAR(8), comment='公告日期')
    S_FINANCING_AMOUNT = Column(Numeric(20, 4), comment='融资金额(人民币)')
    S_VALUATION_AMOUNT = Column(Numeric(20, 4), comment='估值金额(人民币)')
    S_PE = Column(Numeric(20, 4), comment='市盈率(PE)')
    S_PB = Column(Numeric(20, 4), comment='市净率(PB)')
    S_PS = Column(Numeric(20, 4), comment='市销率(PS)')
    S_FINANCING_RATE = Column(Numeric(20, 4), comment='融资费率')
    S_FINANCING_RT = Column(Numeric(20, 4), comment='融资利率')
    S_FINANCING_AMOUNT_US = Column(Numeric(20, 4), comment='融资金额(美元)')
    S_VALUATION_AMOUNT_US = Column(Numeric(20, 4), comment='估值金额(美元)')
    S_EVENT_DESCRIPTION = Column(VARCHAR(1000), comment='事件说明')
    S_FINANCING_PROCESS = Column(Numeric(9, 0), comment='融资进程')


class BSHARECOMPANYHOLDSHARES(Base):
    """中国B股控股参股"""
    __tablename__ = 'BSHARECOMPANYHOLDSHARES'
    OBJECT_ID = Column(VARCHAR(100), primary_key=True, comment='对象ID')
    S_INFO_WINDCODE = Column(VARCHAR(40), comment='Wind代码')
    ANN_DT = Column(VARCHAR(8), comment='公告日期')
    ENDDATE = Column(VARCHAR(8), comment='截止日期')
    S_CAPITALOPERATION_COMPANYNAME = Column(VARCHAR(100), comment='被参控公司名称')
    S_CAPITALOPERATION_COMPANYID = Column(VARCHAR(10), comment='被参控公司ID')
    S_CAPITALOPERATION_COMAINBUS = Column(VARCHAR(1024), comment='被参控公司主营业务')
    RELATIONS_CODE = Column(VARCHAR(40), comment='关系代码')
    S_CAPITALOPERATION_PCT = Column(Numeric(20, 4), comment='直接持股比例')
    VOTING_RIGHTS = Column(Numeric(20, 4), comment='表决权比例')
    S_CAPITALOPERATION_AMOUNT = Column(Numeric(20, 4), comment='投资金额(万元)')
    OPERATIONCRNCY_CODE = Column(VARCHAR(10), comment='货币代码')
    S_CAPITALOPERATION_COREGCAP = Column(Numeric(20, 4), comment='被参股公司注册资本(万元)')
    CAPITALCRNCY_CODE = Column(VARCHAR(10), comment='注册资本货币代码')
    IS_CONSOLIDATE = Column(Numeric(5, 0), comment='是否合并报表')
    NOTCONSOLIDATE_REASON = Column(VARCHAR(500), comment='未纳入合并报表原因')


class BSHAREDESCRIPTION(Base):
    """中国B股基本资料"""
    __tablename__ = 'BSHAREDESCRIPTION'
    OBJECT_ID = Column(VARCHAR(100), primary_key=True, comment='对象ID')
    S_INFO_WINDCODE = Column(VARCHAR(40), comment='Wind代码')
    S_INFO_CODE = Column(VARCHAR(40), comment='交易代码')
    S_INFO_NAME = Column(VARCHAR(50), comment='证券简称')
    S_INFO_COMPNAME = Column(VARCHAR(100), comment='公司中文名称')
    S_INFO_COMPNAMEENG = Column(VARCHAR(100), comment='公司英文名称')
    S_INFO_ISINCODE = Column(VARCHAR(40), comment='ISIN代码')
    S_INFO_EXCHMARKET = Column(VARCHAR(10), comment='交易所')
    S_INFO_LISTBOARD = Column(VARCHAR(10), comment='上市板')
    S_INFO_LISTDATE = Column(VARCHAR(8), comment='上市日期')
    S_INFO_DELISTDATE = Column(VARCHAR(8), comment='退市日期')
    S_INFO_SEDOLCODE = Column(VARCHAR(40), comment='SEDOL代码')
    CRNCY_CODE = Column(VARCHAR(10), comment='货币代码')


class BSHAREDESCRIPTIONZL(Base):
    """中国B股基本资料(增量)"""
    __tablename__ = 'BSHAREDESCRIPTIONZL'
    OBJECT_ID = Column(VARCHAR(100), primary_key=True, comment='对象ID')
    S_INFO_WINDCODE = Column(VARCHAR(40), comment='Wind代码')
    S_INFO_CODE = Column(VARCHAR(40), comment='交易代码')
    S_INFO_NAME = Column(VARCHAR(50), comment='证券简称')
    S_INFO_COMPNAME = Column(VARCHAR(100), comment='公司中文名称')
    S_INFO_COMPNAMEENG = Column(VARCHAR(100), comment='公司英文名称')
    S_INFO_ISINCODE = Column(VARCHAR(40), comment='ISIN代码')
    S_INFO_EXCHMARKET = Column(VARCHAR(10), comment='交易所')
    S_INFO_LISTBOARD = Column(VARCHAR(10), comment='上市板')
    S_INFO_LISTDATE = Column(VARCHAR(8), comment='上市日期')
    S_INFO_DELISTDATE = Column(VARCHAR(8), comment='退市日期')
    S_INFO_SEDOLCODE = Column(VARCHAR(40), comment='SEDOL代码')
    CRNCY_CODE = Column(VARCHAR(10), comment='货币代码')


class BSHAREDIVIDEND(Base):
    """中国B股分红"""
    __tablename__ = 'BSHAREDIVIDEND'
    OBJECT_ID = Column(VARCHAR(100), primary_key=True, comment='对象ID')
    WIND_CODE = Column(VARCHAR(40), comment='Wind代码')
    S_INFO_WINDCODE = Column(VARCHAR(40), comment='Wind代码')
    S_DIV_PROGRESS = Column(VARCHAR(10), comment='方案进度')
    STK_DVD_PER_SH = Column(Numeric(20, 4), comment='每股送转')
    CASH_DVD_PER_SH_PRE_TAX = Column(Numeric(20, 6), comment='每股派息(税前)(元)')
    CASH_DVD_PER_SH_AFTER_TAX = Column(Numeric(20, 6), comment='每股派息(税后)(元)')
    EQY_RECORD_DT = Column(VARCHAR(8), comment='股权登记日')
    EX_DT = Column(VARCHAR(8), comment='除权除息日')
    DVD_PAYOUT_DT = Column(VARCHAR(8), comment='派息日')
    LISTING_DT_OF_DVD_SHR = Column(VARCHAR(8), comment='红股上市日')
    S_DIV_PRELANDATE = Column(VARCHAR(8), comment='预案公告日')
    S_DIV_SMTGDATE = Column(VARCHAR(8), comment='股东大会公告日')
    DVD_ANN_DT = Column(VARCHAR(8), comment='分红实施公告日')
    S_DIV_BASEDATE = Column(VARCHAR(8), comment='基准日期')
    S_DIV_BASESHARE = Column(Numeric(20, 4), comment='基准股本(万股)')
    CRNCY_CODE = Column(VARCHAR(10), comment='货币代码')
    ANN_DT = Column(VARCHAR(8), comment='最新公告日期')
    IS_CHANGED = Column(Numeric(5, 0), comment='方案是否变更')
    REPORT_PERIOD = Column(VARCHAR(8), comment='分红年度')
    S_DIV_CHANGE = Column(VARCHAR(800), comment='方案变更说明')
    S_DIV_BONUSRATE = Column(Numeric(20, 8), comment='每股送股比例')
    S_DIV_CONVERSEDRATE = Column(Numeric(20, 8), comment='每股转增比例')
    EXCHANGERATE_DT = Column(VARCHAR(8), comment='汇率折算日')
    EXCHANGERATE = Column(Numeric(20, 8), comment='汇率(公布)')


class BSHAREEODDERIVATIVEINDICATOR(Base):
    """中国B股日行情估值指标"""
    __tablename__ = 'BSHAREEODDERIVATIVEINDICATOR'
    OBJECT_ID = Column(VARCHAR(100), primary_key=True, comment='对象ID')
    S_INFO_WINDCODE = Column(VARCHAR(40), comment='Wind代码')
    TRADE_DT = Column(VARCHAR(8), comment='交易日期')
    CRNCY_CODE = Column(VARCHAR(10), comment='货币代码')
    S_VAL_MV = Column(Numeric(20, 4), comment='当日总市值')
    S_DQ_MV = Column(Numeric(20, 4), comment='当日流通市值')
    S_PQ_HIGH_52W = Column(Numeric(20, 4), comment='52周最高价')
    S_PQ_LOW_52W = Column(Numeric(20, 4), comment='52周最低价')
    S_VAL_PE = Column(Numeric(20, 4), comment='市盈率(PE)')
    S_VAL_PB_NEW = Column(Numeric(20, 4), comment='市净率(PB)')
    S_VAL_PE_TTM = Column(Numeric(20, 4), comment='市盈率(PE,TTM)')
    S_VAL_PCF_OCF = Column(Numeric(20, 4), comment='市现率(PCF,经营现金流)')
    S_VAL_PCF_OCFTTM = Column(Numeric(20, 4), comment='市现率(PCF,经营现金流TTM)')
    S_VAL_PCF_NCF = Column(Numeric(20, 4), comment='市现率(PCF,现金净流量)')
    S_VAL_PCF_NCFTTM = Column(Numeric(20, 4), comment='市现率(PCF,现金净流量TTM)')
    S_VAL_PS = Column(Numeric(20, 4), comment='市销率(PS)')
    S_VAL_PS_TTM = Column(Numeric(20, 4), comment='市销率(PS,TTM)')
    S_DQ_TURN = Column(Numeric(20, 4), comment='换手率')
    S_DQ_FREETURNOVER = Column(Numeric(20, 4), comment='换手率(基准.自由流通股本)')
    TOT_SHR_TODAY = Column(Numeric(20, 4), comment='当日总股本')
    FLOAT_A_SHR_TODAY = Column(Numeric(20, 4), comment='当日流通股本')
    S_DQ_CLOSE_TODAY = Column(Numeric(20, 4), comment='当日收盘价')
    S_PRICE_DIV_DPS = Column(Numeric(20, 4), comment='股价/每股派息')


class BSHAREEODPRICES(Base):
    """中国B股日行情"""
    __tablename__ = 'BSHAREEODPRICES'
    OBJECT_ID = Column(VARCHAR(100), primary_key=True, comment='对象ID')
    S_INFO_WINDCODE = Column(VARCHAR(40), comment='Wind代码')
    TRADE_DT = Column(VARCHAR(8), comment='交易日期')
    CRNCY_CODE = Column(VARCHAR(10), comment='货币代码')
    S_DQ_PRECLOSE = Column(Numeric(20, 4), comment='昨收盘价(元)')
    S_DQ_OPEN = Column(Numeric(20, 4), comment='开盘价(元)')
    S_DQ_HIGH = Column(Numeric(20, 4), comment='最高价(元)')
    S_DQ_LOW = Column(Numeric(20, 4), comment='最低价(元)')
    S_DQ_CLOSE = Column(Numeric(20, 4), comment='收盘价(元)')
    S_DQ_CHANGE = Column(Numeric(20, 4), comment='涨跌(元)')
    S_DQ_PCTCHANGE = Column(Numeric(20, 4), comment='涨跌幅(%)')
    S_DQ_VOLUME = Column(Numeric(20, 4), comment='成交量(手)')
    S_DQ_AMOUNT = Column(Numeric(20, 4), comment='成交金额(千元)')
    S_DQ_ADJPRECLOSE = Column(Numeric(20, 4), comment='复权昨收盘价(元)')
    S_DQ_ADJOPEN = Column(Numeric(20, 4), comment='复权开盘价(元)')
    S_DQ_ADJHIGH = Column(Numeric(20, 4), comment='复权最高价(元)')
    S_DQ_ADJLOW = Column(Numeric(20, 4), comment='复权最低价(元)')
    S_DQ_ADJCLOSE = Column(Numeric(20, 4), comment='复权收盘价(元)')
    S_DQ_ADJFACTOR = Column(Numeric(20, 6), comment='复权因子')
    S_DQ_AVGPRICE = Column(Numeric(20, 4), comment='均价(VWAP)')
    S_DQ_TRADESTATUS = Column(VARCHAR(10), comment='交易状态')
    TRADES_COUNT = Column(Numeric(20, 4), comment='成交笔数')


class BSHAREFINANCIALINDICATOR(Base):
    """中国B股财务指标"""
    __tablename__ = 'BSHAREFINANCIALINDICATOR'
    OBJECT_ID = Column(VARCHAR(100), primary_key=True, comment='对象ID')
    S_INFO_WINDCODE = Column(VARCHAR(40), comment='Wind代码')
    WIND_CODE = Column(VARCHAR(40), comment='Wind代码')
    ANN_DT = Column(VARCHAR(8), comment='公告日期')
    REPORT_PERIOD = Column(VARCHAR(8), comment='报告期')
    CRNCY_CODE = Column(VARCHAR(10), comment='货币代码')
    S_FA_EXTRAORDINARY = Column(Numeric(20, 4), comment='非经常性损益')
    S_FA_DEDUCTEDPROFIT = Column(Numeric(20, 4), comment='扣除非经常性损益后的净利润')
    S_FA_GROSSMARGIN = Column(Numeric(20, 4), comment='毛利')
    S_FA_OPERATEINCOME = Column(Numeric(20, 4), comment='经营活动净收益')
    S_FA_INVESTINCOME = Column(Numeric(20, 4), comment='价值变动净收益')
    S_STMNOTE_FINEXP = Column(Numeric(20, 4), comment='利息费用')
    S_STM_IS = Column(Numeric(20, 4), comment='折旧与摊销')
    S_FA_EBIT = Column(Numeric(20, 4), comment='息税前利润')
    S_FA_EBITDA = Column(Numeric(20, 4), comment='息税折旧摊销前利润')
    S_FA_FCFF = Column(Numeric(20, 4), comment='企业自由现金流量(FCFF)')
    S_FA_FCFE = Column(Numeric(20, 4), comment='股权自由现金流量(FCFE)')
    S_FA_EXINTERESTDEBT_CURRENT = Column(Numeric(20, 4), comment='无息流动负债')
    S_FA_EXINTERESTDEBT_NONCURRENT = Column(Numeric(20, 4), comment='无息非流动负债')
    S_FA_INTERESTDEBT = Column(Numeric(20, 4), comment='带息债务')
    S_FA_NETDEBT = Column(Numeric(20, 4), comment='净债务')
    S_FA_TANGIBLEASSET = Column(Numeric(20, 4), comment='有形资产')
    S_FA_WORKINGCAPITAL = Column(Numeric(20, 4), comment='营运资金')
    S_FA_NETWORKINGCAPITAL = Column(Numeric(20, 4), comment='营运流动资本')
    S_FA_INVESTCAPITAL = Column(Numeric(20, 4), comment='全部投入资本')
    S_FA_RETAINEDEARNINGS = Column(Numeric(20, 4), comment='留存收益')
    S_FA_EPS_BASIC = Column(Numeric(20, 4), comment='基本每股收益')
    S_FA_EPS_DILUTED = Column(Numeric(20, 4), comment='稀释每股收益')
    S_FA_EPS_DILUTED2 = Column(Numeric(20, 4), comment='期末摊薄每股收益')
    S_FA_BPS = Column(Numeric(20, 4), comment='每股净资产')
    S_FA_OCFPS = Column(Numeric(20, 4), comment='每股经营活动产生的现金流量净额')
    S_FA_GRPS = Column(Numeric(20, 4), comment='每股营业总收入')
    S_FA_ORPS = Column(Numeric(20, 4), comment='每股营业收入')
    S_FA_SURPLUSCAPITALPS = Column(Numeric(20, 4), comment='每股资本公积')
    S_FA_SURPLUSRESERVEPS = Column(Numeric(20, 4), comment='每股盈余公积')
    S_FA_UNDISTRIBUTEDPS = Column(Numeric(20, 4), comment='每股未分配利润')
    S_FA_RETAINEDPS = Column(Numeric(20, 4), comment='每股留存收益')
    S_FA_CFPS = Column(Numeric(20, 4), comment='每股现金流量净额')
    S_FA_EBITPS = Column(Numeric(20, 4), comment='每股息税前利润')
    S_FA_FCFFPS = Column(Numeric(20, 4), comment='每股企业自由现金流量')
    S_FA_FCFEPS = Column(Numeric(20, 4), comment='每股股东自由现金流量')
    S_FA_NETPROFITMARGIN = Column(Numeric(20, 4), comment='销售净利率')
    S_FA_GROSSPROFITMARGIN = Column(Numeric(20, 4), comment='销售毛利率')
    S_FA_COGSTOSALES = Column(Numeric(20, 4), comment='销售成本率')
    S_FA_EXPENSETOSALES = Column(Numeric(20, 4), comment='销售期间费用率')
    S_FA_PROFITTOGR = Column(Numeric(20, 4), comment='净利润/营业总收入')
    S_FA_SALEEXPENSETOGR = Column(Numeric(20, 4), comment='销售费用/营业总收入')
    S_FA_ADMINEXPENSETOGR = Column(Numeric(20, 4), comment='管理费用/营业总收入')
    S_FA_FINAEXPENSETOGR = Column(Numeric(20, 4), comment='财务费用/营业总收入')
    S_FA_IMPAIRTOGR_TTM = Column(Numeric(20, 4), comment='资产减值损失/营业总收入')
    S_FA_GCTOGR = Column(Numeric(20, 4), comment='营业总成本/营业总收入')
    S_FA_OPTOGR = Column(Numeric(20, 4), comment='营业利润/营业总收入')
    S_FA_EBITTOGR = Column(Numeric(20, 4), comment='息税前利润/营业总收入')
    S_FA_ROE = Column(Numeric(20, 4), comment='净资产收益率')
    S_FA_ROE_DEDUCTED = Column(Numeric(20, 4), comment='净资产收益率(扣除非经常损益)')
    S_FA_ROA2 = Column(Numeric(20, 4), comment='总资产报酬率')
    S_FA_ROA = Column(Numeric(20, 4), comment='总资产净利润')
    S_FA_ROIC = Column(Numeric(20, 4), comment='投入资本回报率')
    S_FA_ROE_YEARLY = Column(Numeric(20, 4), comment='年化净资产收益率')
    S_FA_ROA2_YEARLY = Column(Numeric(20, 4), comment='年化总资产报酬率')
    S_FA_ROE_AVG = Column(Numeric(20, 4), comment='平均净资产收益率(增发条件)')
    S_FA_OPERATEINCOMETOEBT = Column(Numeric(20, 4), comment='经营活动净收益/利润总额')
    S_FA_INVESTINCOMETOEBT = Column(Numeric(20, 4), comment='价值变动净收益/利润总额')
    S_FA_NONOPERATEPROFITTOEBT = Column(Numeric(20, 4), comment='营业外收支净额/利润总额')
    S_FA_TAXTOEBT = Column(Numeric(20, 4), comment='所得税/利润总额')
    S_FA_DEDUCTEDPROFITTOPROFIT = Column(Numeric(20, 4), comment='扣除非经常损益后的净利润/净利润')
    S_FA_SALESCASHINTOOR = Column(Numeric(20, 4), comment='销售商品提供劳务收到的现金/营业收入')
    S_FA_OCFTOOR = Column(Numeric(20, 4), comment='经营活动产生的现金流量净额/营业收入')
    S_FA_OCFTOOPERATEINCOME = Column(Numeric(20, 4), comment='经营活动产生的现金流量净额/经营活动净收益')
    S_FA_CAPITALIZEDTODA = Column(Numeric(20, 4), comment='资本支出/折旧和摊销')
    S_FA_DEBTTOASSETS = Column(Numeric(20, 4), comment='资产负债率')
    S_FA_ASSETSTOEQUITY = Column(Numeric(20, 4), comment='权益乘数')
    S_FA_DUPONT_ASSETSTOEQUITY = Column(Numeric(20, 4), comment='权益乘数(用于杜邦分析)')
    S_FA_CATOASSETS = Column(Numeric(20, 4), comment='流动资产/总资产')
    S_FA_NCATOASSETS = Column(Numeric(20, 4), comment='非流动资产/总资产')
    S_FA_TANGIBLEASSETSTOASSETS = Column(Numeric(20, 4), comment='有形资产/总资产')
    S_FA_INTDEBTTOTOTALCAP = Column(Numeric(20, 4), comment='带息债务/全部投入资本')
    S_FA_EQUITYTOTOTALCAPITAL = Column(Numeric(20, 4), comment='归属于母公司的股东权益/全部投入资本')
    S_FA_CURRENTDEBTTODEBT = Column(Numeric(20, 4), comment='流动负债/负债合计')
    S_FA_LONGDEBTODEBT = Column(Numeric(20, 4), comment='非流动负债/负债合计')
    S_FA_CURRENT = Column(Numeric(20, 4), comment='流动比率')
    S_FA_QUICK = Column(Numeric(20, 4), comment='速动比率')
    S_FA_CASHRATIO = Column(Numeric(20, 4), comment='保守速动比率')
    S_FA_OCFTOSHORTDEBT = Column(Numeric(20, 4), comment='经营活动产生的现金流量净额/流动负债')
    S_FA_DEBTTOEQUITY = Column(Numeric(20, 4), comment='产权比率')
    S_FA_EQUITYTODEBT = Column(Numeric(20, 4), comment='归属于母公司的股东权益/负债合计')
    S_FA_EQUITYTOINTERESTDEBT = Column(Numeric(20, 4), comment='归属于母公司的股东权益/带息债务')
    S_FA_TANGIBLEASSETTODEBT = Column(Numeric(20, 4), comment='有形资产/负债合计')
    S_FA_TANGASSETTOINTDEBT = Column(Numeric(20, 4), comment='有形资产/带息债务')
    S_FA_TANGIBLEASSETTONETDEBT = Column(Numeric(20, 4), comment='有形资产/净债务')
    S_FA_OCFTODEBT = Column(Numeric(20, 4), comment='经营活动产生的现金流量净额/负债合计')
    S_FA_OCFTOINTERESTDEBT = Column(Numeric(20, 4), comment='经营活动产生的现金流量净额/带息债务')
    S_FA_OCFTONETDEBT = Column(Numeric(20, 4), comment='经营活动产生的现金流量净额/净债务')
    S_FA_EBITTOINTEREST = Column(Numeric(20, 4), comment='已获利息倍数(EBIT/利息费用)')
    S_FA_LONGDEBTTOWORKINGCAPITAL = Column(Numeric(20, 4), comment='长期债务与营运资金比率')
    S_FA_EBITDATODEBT = Column(Numeric(20, 4), comment='息税折旧摊销前利润/负债合计')
    S_FA_TURNDAYS = Column(Numeric(20, 4), comment='营业周期')
    S_FA_INVTURNDAYS = Column(Numeric(20, 4), comment='存货周转天数')
    S_FA_ARTURNDAYS = Column(Numeric(20, 4), comment='应收账款周转天数')
    S_FA_INVTURN = Column(Numeric(20, 4), comment='存货周转率')
    S_FA_ARTURN = Column(Numeric(20, 4), comment='应收账款周转率')
    S_FA_CATURN = Column(Numeric(20, 4), comment='流动资产周转率')
    S_FA_FATURN = Column(Numeric(20, 4), comment='固定资产周转率')
    S_FA_ASSETSTURN = Column(Numeric(20, 4), comment='总资产周转率')
    S_FA_ROA_YEARLY = Column(Numeric(20, 4), comment='年化总资产净利率')
    S_FA_DUPONT_ROA = Column(Numeric(20, 4), comment='总资产净利率(杜邦分析)')
    S_STM_BS = Column(Numeric(20, 4), comment='固定资产合计')
    S_FA_PREFINEXPENSE_OPPROFIT = Column(Numeric(20, 4), comment='扣除财务费用前营业利润')
    S_FA_NONOPPROFIT = Column(Numeric(20, 4), comment='非营业利润')
    S_FA_OPTOEBT = Column(Numeric(20, 4), comment='营业利润／利润总额')
    S_FA_NOPTOEBT = Column(Numeric(20, 4), comment='非营业利润／利润总额')
    S_FA_OCFTOPROFIT = Column(Numeric(20, 4), comment='经营活动产生的现金流量净额／营业利润')
    S_FA_CASHTOLIQDEBT = Column(Numeric(20, 4), comment='货币资金／流动负债')
    S_FA_CASHTOLIQDEBTWITHINTEREST = Column(Numeric(20, 4), comment='货币资金／带息流动负债')
    S_FA_OPTOLIQDEBT = Column(Numeric(20, 4), comment='营业利润／流动负债')
    S_FA_OPTODEBT = Column(Numeric(20, 4), comment='营业利润／负债合计')
    S_FA_ROIC_YEARLY = Column(Numeric(20, 4), comment='年化投入资本回报率')
    S_FA_TOT_FATURN = Column(Numeric(20, 4), comment='固定资产合计周转率')
    S_FA_PROFITTOOP = Column(Numeric(20, 4), comment='利润总额／营业收入')
    S_QFA_OPERATEINCOME = Column(Numeric(20, 4), comment='单季度.经营活动净收益')
    S_QFA_INVESTINCOME = Column(Numeric(20, 4), comment='单季度.价值变动净收益')
    S_QFA_DEDUCTEDPROFIT = Column(Numeric(20, 4), comment='单季度.扣除非经常损益后的净利润')
    S_QFA_EPS = Column(Numeric(20, 4), comment='单季度.每股收益')
    S_QFA_NETPROFITMARGIN = Column(Numeric(20, 4), comment='单季度.销售净利率')
    S_QFA_GROSSPROFITMARGIN = Column(Numeric(20, 4), comment='单季度.销售毛利率')
    S_QFA_EXPENSETOSALES = Column(Numeric(20, 4), comment='单季度.销售期间费用率')
    S_QFA_PROFITTOGR = Column(Numeric(20, 4), comment='单季度.净利润／营业总收入')
    S_QFA_SALEEXPENSETOGR = Column(Numeric(20, 4), comment='单季度.销售费用／营业总收入')
    S_QFA_ADMINEXPENSETOGR = Column(Numeric(20, 4), comment='单季度.管理费用／营业总收入')
    S_QFA_FINAEXPENSETOGR = Column(Numeric(20, 4), comment='单季度.财务费用／营业总收入')
    S_QFA_IMPAIRTOGR_TTM = Column(Numeric(20, 4), comment='单季度.资产减值损失／营业总收入')
    S_QFA_GCTOGR = Column(Numeric(20, 4), comment='单季度.营业总成本／营业总收入')
    S_QFA_OPTOGR = Column(Numeric(20, 4), comment='单季度.营业利润／营业总收入')
    S_QFA_ROE = Column(Numeric(20, 4), comment='单季度.净资产收益率')
    S_QFA_ROE_DEDUCTED = Column(Numeric(20, 4), comment='单季度.净资产收益率(扣除非经常损益)')
    S_QFA_ROA = Column(Numeric(20, 4), comment='单季度.总资产净利润')
    S_QFA_OPERATEINCOMETOEBT = Column(Numeric(20, 4), comment='单季度.经营活动净收益／利润总额')
    S_QFA_INVESTINCOMETOEBT = Column(Numeric(20, 4), comment='单季度.价值变动净收益／利润总额')
    S_QFA_DEDUCTEDPROFITTOPROFIT = Column(Numeric(20, 4), comment='单季度.扣除非经常损益后的净利润／净利润')
    S_QFA_SALESCASHINTOOR = Column(Numeric(20, 4), comment='单季度.销售商品提供劳务收到的现金／营业收入')
    S_QFA_OCFTOSALES = Column(Numeric(20, 4), comment='单季度.经营活动产生的现金流量净额／营业收入')
    S_QFA_OCFTOOR = Column(Numeric(20, 4), comment='单季度.经营活动产生的现金流量净额／经营活动净收益')
    S_FA_YOYEPS_BASIC = Column(Numeric(20, 4), comment='同比增长率-基本每股收益(%)')
    S_FA_YOYEPS_DILUTED = Column(Numeric(20, 4), comment='同比增长率-稀释每股收益(%)')
    S_FA_YOYOCFPS = Column(Numeric(20, 4), comment='同比增长率-每股经营活动产生的现金流量净额(%)')
    S_FA_YOYOP = Column(Numeric(20, 4), comment='同比增长率-营业利润(%)')
    S_FA_YOYEBT = Column(Numeric(20, 4), comment='同比增长率-利润总额(%)')
    S_FA_YOYNETPROFIT = Column(Numeric(20, 4), comment='同比增长率-归属母公司股东的净利润(%)')
    S_FA_YOYNETPROFIT_DEDUCTED = Column(Numeric(20, 4), comment='同比增长率-归属母公司股东的净利润-扣除非经常损益(%)')
    S_FA_YOYOCF = Column(Numeric(20, 4), comment='同比增长率-经营活动产生的现金流量净额(%)')
    S_FA_YOYROE = Column(Numeric(20, 4), comment='同比增长率-净资产收益率(摊薄)(%)')
    S_FA_YOYBPS = Column(Numeric(20, 4), comment='相对年初增长率-每股净资产(%)')
    S_FA_YOYASSETS = Column(Numeric(20, 4), comment='相对年初增长率-资产总计(%)')
    S_FA_YOYEQUITY = Column(Numeric(20, 4), comment='相对年初增长率-归属母公司的股东权益(%)')
    S_FA_YOY_TR = Column(Numeric(20, 4), comment='营业总收入同比增长率(%)')
    S_FA_YOY_OR = Column(Numeric(20, 4), comment='营业收入同比增长率(%)')
    S_QFA_YOYGR = Column(Numeric(20, 4), comment='单季度.营业总收入同比增长率(%)')
    S_QFA_CGRGR = Column(Numeric(20, 4), comment='单季度.营业总收入环比增长率(%)')
    S_QFA_YOYSALES = Column(Numeric(20, 4), comment='单季度.营业收入同比增长率(%)')
    S_QFA_CGRSALES = Column(Numeric(20, 4), comment='单季度.营业收入环比增长率(%)')
    S_QFA_YOYOP = Column(Numeric(20, 4), comment='单季度.营业利润同比增长率(%)')
    S_QFA_CGROP = Column(Numeric(20, 4), comment='单季度.营业利润环比增长率(%)')
    S_QFA_YOYPROFIT = Column(Numeric(20, 4), comment='单季度.净利润同比增长率(%)')
    S_QFA_CGRPROFIT = Column(Numeric(20, 4), comment='单季度.净利润环比增长率(%)')
    S_QFA_YOYNETPROFIT = Column(Numeric(20, 4), comment='单季度.归属母公司股东的净利润同比增长率(%)')
    S_QFA_CGRNETPROFIT = Column(Numeric(20, 4), comment='单季度.归属母公司股东的净利润环比增长率(%)')
    S_FA_YOY_EQUITY = Column(Numeric(20, 4), comment='净资产(同比增长率)')
    S_INFO_COMPCODE = Column(VARCHAR(10), comment='公司ID')


class BSHAREFREEFLOATCALENDAR(Base):
    """中国B股限售股流通日历"""
    __tablename__ = 'BSHAREFREEFLOATCALENDAR'
    OBJECT_ID = Column(VARCHAR(100), primary_key=True, comment='对象ID')
    S_INFO_WINDCODE = Column(VARCHAR(40), comment='Wind代码')
    S_INFO_LISTDATE = Column(VARCHAR(8), comment='限售股上市日期')
    ANN_DT = Column(VARCHAR(8), comment='公告日期')
    S_SHARE_LST = Column(Numeric(20, 4), comment='上市股份数量（万股）')
    S_SHARE_NONLST = Column(Numeric(20, 4), comment='未上市股份数量（万股）')
    S_SHARE_UNRESTRICTED = Column(Numeric(20, 4), comment='无限售条件股份数量（万股）')


class BSHAREFUNDUSING(Base):
    """中国B股募集资金用途"""
    __tablename__ = 'BSHAREFUNDUSING'
    OBJECT_ID = Column(VARCHAR(100), primary_key=True, comment='对象ID')
    S_INFO_COMPCODE = Column(VARCHAR(38), comment='公司ID')
    FINANCING_EVENTS_TYPE = Column(VARCHAR(100), comment='融资事件类型')
    MONEY_RAISED_AMOUNT = Column(Numeric(20, 4), comment='货币募集金额')
    NON_CURRENCY_RAISE_AMOUNT = Column(Numeric(20, 4), comment='非货币募集金额')
    ISSUE_COST = Column(Numeric(20, 4), comment='发行费用')
    ACTUAL_FUNDRAISING_AMOUNT = Column(Numeric(20, 4), comment='实际募资金额')
    CURRENCY_CODE = Column(VARCHAR(10), comment='货币代码')
    ANN_DATE = Column(VARCHAR(8), comment='公告日期')
    ITEM_NUMBER = Column(VARCHAR(20), comment='项目序号')
    INVESTMENT_PROJECTS = Column(VARCHAR(100), comment='投资项目')
    PLAN_INVEST = Column(Numeric(20, 4), comment='项目总计划投入资金')
    ISSUER_PLAN_INVEST = Column(Numeric(20, 4), comment='募资主体计划投入资金')
    ISSUER_PLAN_FUNDS_INVESTMENT = Column(Numeric(20, 4), comment='募资主体计划投入募集资金')
    FUNDS_HAS_INVESTED = Column(Numeric(20, 4), comment='已投入募集资金')
    IS_CHANGE = Column(Numeric(1, 0), comment='是否变更')
    NEW_ANN_DATE = Column(VARCHAR(8), comment='最新公告日期')


class BSHAREHOLDERSMEETING(Base):
    """中国B股召开股东大会"""
    __tablename__ = 'BSHAREHOLDERSMEETING'
    OBJECT_ID = Column(VARCHAR(100), primary_key=True, comment='对象ID')
    S_INFO_WINDCODE = Column(VARCHAR(40), comment='Wind代码')
    ANN_DT = Column(VARCHAR(8), comment='公告日期')
    MEETING_DT = Column(VARCHAR(8), comment='会议日期')
    MEETING_TYPE = Column(VARCHAR(20), comment='会议类型')
    VOTINGCODE = Column(Numeric(9, 0), comment='投票通道代码')
    SMTGRECDATE = Column(VARCHAR(8), comment='股东大会股权登记日')
    SPOTMTGSTARTDATE = Column(VARCHAR(8), comment='会议登记起始日')
    SPOTMTGENDDATE = Column(VARCHAR(8), comment='会议登记截止日')
    IS_INTNET = Column(VARCHAR(1), comment='是否可以网络投票')
    INTNETCODE = Column(VARCHAR(10), comment='网络投票代码')
    INTNETNAME = Column(VARCHAR(20), comment='网络投票简称')
    MEETING_CONTENT = Column(VARCHAR, comment='会议内容')
    CHANGE_HIS = Column(VARCHAR(100), comment='变更历史')
    MEETEVENT_ID = Column(VARCHAR(40), comment='会议事件ID')
    IS_NEW = Column(Numeric(5, 0), comment='最新标志')
    INTNET_STARTDATE = Column(VARCHAR(8), comment='互联网投票起始日')
    INTNET_ENDDATE = Column(VARCHAR(8), comment='互联网投票终止日')


class BSHAREHOLDINGOPERATE(Base):
    """中国B股控股参股公司经营情况"""
    __tablename__ = 'BSHAREHOLDINGOPERATE'
    OBJECT_ID = Column(VARCHAR(38), primary_key=True, comment='对象ID')
    S_INFO_COMPCODE = Column(VARCHAR(10), comment='公司id')
    ANN_DT = Column(VARCHAR(8), comment='公告日期')
    REPORT_PERIOD = Column(VARCHAR(8), comment='截止日期')
    S_CAPITALOPERATION_COMPANYNAME = Column(VARCHAR(80), comment='被参控公司名称')
    S_TOT_ASSETS = Column(Numeric(24, 8), comment='资产规模')
    S_NET_PROFIT = Column(Numeric(24, 8), comment='净利润')
    CRNCY_CODE = Column(VARCHAR(10), comment='货币代码')
    S_NET_ASSETS = Column(Numeric(24, 8), comment='净资产')
    S_TOT_LIAB = Column(Numeric(24, 8), comment='负债总额')
    S_OPER_REV = Column(Numeric(24, 8), comment='营业收入')
    S_TOT_PROFIT = Column(Numeric(24, 8), comment='利润总额')


class BSHAREILLEGALITY(Base):
    """中国B股违规事件"""
    __tablename__ = 'BSHAREILLEGALITY'
    OBJECT_ID = Column(VARCHAR(100), primary_key=True, comment='对象ID')
    S_INFO_WINDCODE = Column(VARCHAR(40), comment='Wind代码')
    S_INFO_COMPCODE = Column(VARCHAR(40), comment='公司ID')
    ANN_DT = Column(VARCHAR(8), comment='公告日期')
    ILLEG_TYPE = Column(VARCHAR(100), comment='违规类型')
    SUBJECT_TYPE = Column(Numeric(9, 0), comment='主体类别代码')
    SUBJECT = Column(VARCHAR(100), comment='违规主体')
    RELATION_TYPE = Column(Numeric(9, 0), comment='与上市公司的关系')
    BEHAVIOR = Column(VARCHAR, comment='违规行为')
    DISPOSAL_DT = Column(VARCHAR(8), comment='处罚日期')
    DISPOSAL_TYPE = Column(VARCHAR(100), comment='处分类型')
    METHOD = Column(VARCHAR(2000), comment='处分措施')
    PROCESSOR = Column(VARCHAR(200), comment='处理人')
    AMOUNT = Column(Numeric(20, 4), comment='处罚金额(元)')
    BAN_YEAR = Column(Numeric(20, 4), comment='市场禁入期限(年)')
    REF_RULE = Column(VARCHAR(1000), comment='相关法规')
    ILLEG_TYPE_CODE = Column(VARCHAR(1000), comment='违规类型代码')
    ANN_ID = Column(Numeric(11, 0), comment='公告id')


class BSHAREINCOME(Base):
    """中国B股利润表"""
    __tablename__ = 'BSHAREINCOME'
    OBJECT_ID = Column(VARCHAR(100), primary_key=True, comment='对象ID')
    S_INFO_WINDCODE = Column(VARCHAR(40), comment='Wind代码')
    WIND_CODE = Column(VARCHAR(40), comment='Wind代码')
    ANN_DT = Column(VARCHAR(8), comment='公告日期')
    REPORT_PERIOD = Column(VARCHAR(8), comment='报告期')
    STATEMENT_TYPE = Column(VARCHAR(10), comment='报表类型')
    CRNCY_CODE = Column(VARCHAR(10), comment='货币代码')
    TOT_OPER_REV = Column(Numeric(20, 4), comment='营业总收入')
    OPER_REV = Column(Numeric(20, 4), comment='营业收入')
    INT_INC = Column(Numeric(20, 4), comment='利息收入')
    NET_INT_INC = Column(Numeric(20, 4), comment='利息净收入')
    INSUR_PREM_UNEARNED = Column(Numeric(20, 4), comment='已赚保费')
    HANDLING_CHRG_COMM_INC = Column(Numeric(20, 4), comment='手续费及佣金收入')
    NET_HANDLING_CHRG_COMM_INC = Column(Numeric(20, 4), comment='手续费及佣金净收入')
    NET_INC_OTHER_OPS = Column(Numeric(20, 4), comment='其他经营净收益')
    PLUS_NET_INC_OTHER_BUS = Column(Numeric(20, 4), comment='加:其他业务净收益')
    PREM_INC = Column(Numeric(20, 4), comment='保费业务收入')
    LESS_CEDED_OUT_PREM = Column(Numeric(20, 4), comment='减:分出保费')
    CHG_UNEARNED_PREM_RES = Column(Numeric(20, 4), comment='提取未到期责任准备金')
    INCL_REINSURANCE_PREM_INC = Column(Numeric(20, 4), comment='其中:分保费收入')
    NET_INC_SEC_TRADING_BROK_BUS = Column(Numeric(20, 4), comment='代理买卖证券业务净收入')
    NET_INC_SEC_UW_BUS = Column(Numeric(20, 4), comment='证券承销业务净收入')
    NET_INC_EC_ASSET_MGMT_BUS = Column(Numeric(20, 4), comment='受托客户资产管理业务净收入')
    OTHER_BUS_INC = Column(Numeric(20, 4), comment='其他业务收入')
    PLUS_NET_GAIN_CHG_FV = Column(Numeric(20, 4), comment='加:公允价值变动净收益')
    PLUS_NET_INVEST_INC = Column(Numeric(20, 4), comment='加:投资净收益')
    INCL_INC_INVEST_ASSOC_JV_ENTP = Column(Numeric(20, 4), comment='其中:对联营企业和合营企业的投资收益')
    PLUS_NET_GAIN_FX_TRANS = Column(Numeric(20, 4), comment='加:汇兑净收益')
    TOT_OPER_COST = Column(Numeric(20, 4), comment='营业总成本')
    LESS_OPER_COST = Column(Numeric(20, 4), comment='减:营业成本')
    LESS_INT_EXP = Column(Numeric(20, 4), comment='减:利息支出')
    LESS_HANDLING_CHRG_COMM_EXP = Column(Numeric(20, 4), comment='减:手续费及佣金支出')
    LESS_TAXES_SURCHARGES_OPS = Column(Numeric(20, 4), comment='减:营业税金及附加')
    LESS_SELLING_DIST_EXP = Column(Numeric(20, 4), comment='减:销售费用')
    LESS_GERL_ADMIN_EXP = Column(Numeric(20, 4), comment='减:管理费用')
    LESS_FIN_EXP = Column(Numeric(20, 4), comment='减:财务费用')
    LESS_IMPAIR_LOSS_ASSETS = Column(Numeric(20, 4), comment='减:资产减值损失')
    PREPAY_SURR = Column(Numeric(20, 4), comment='退保金')
    TOT_CLAIM_EXP = Column(Numeric(20, 4), comment='赔付总支出')
    CHG_INSUR_CONT_RSRV = Column(Numeric(20, 4), comment='提取保险责任准备金')
    DVD_EXP_INSURED = Column(Numeric(20, 4), comment='保户红利支出')
    REINSURANCE_EXP = Column(Numeric(20, 4), comment='分保费用')
    OPER_EXP = Column(Numeric(20, 4), comment='营业支出')
    LESS_CLAIM_RECB_REINSURER = Column(Numeric(20, 4), comment='减:摊回赔付支出')
    LESS_INS_RSRV_RECB_REINSURER = Column(Numeric(20, 4), comment='减:摊回保险责任准备金')
    LESS_EXP_RECB_REINSURER = Column(Numeric(20, 4), comment='减:摊回分保费用')
    OTHER_BUS_COST = Column(Numeric(20, 4), comment='其他业务成本')
    OPER_PROFIT = Column(Numeric(20, 4), comment='营业利润')
    PLUS_NON_OPER_REV = Column(Numeric(20, 4), comment='加:营业外收入')
    LESS_NON_OPER_EXP = Column(Numeric(20, 4), comment='减:营业外支出')
    IL_NET_LOSS_DISP_NONCUR_ASSET = Column(Numeric(20, 4), comment='其中:减:非流动资产处置净损失')
    TOT_PROFIT = Column(Numeric(20, 4), comment='利润总额')
    INC_TAX = Column(Numeric(20, 4), comment='所得税')
    UNCONFIRMED_INVEST_LOSS = Column(Numeric(20, 4), comment='未确认投资损失')
    NET_PROFIT_INCL_MIN_INT_INC = Column(Numeric(20, 4), comment='净利润(含少数股东损益)')
    NET_PROFIT_EXCL_MIN_INT_INC = Column(Numeric(20, 4), comment='净利润(不含少数股东损益)')
    MINORITY_INT_INC = Column(Numeric(20, 4), comment='少数股东损益')
    OTHER_COMPREH_INC = Column(Numeric(20, 4), comment='其他综合收益')
    TOT_COMPREH_INC = Column(Numeric(20, 4), comment='综合收益总额')
    TOT_COMPREH_INC_PARENT_COMP = Column(Numeric(20, 4), comment='综合收益总额(母公司)')
    TOT_COMPREH_INC_MIN_SHRHLDR = Column(Numeric(20, 4), comment='综合收益总额(少数股东)')
    EBIT = Column(Numeric(20, 4), comment='息税前利润')
    EBITDA = Column(Numeric(20, 4), comment='息税折旧摊销前利润')
    NET_PROFIT_AFTER_DED_NR_LP = Column(Numeric(20, 4), comment='扣除非经常性损益后净利润')
    NET_PROFIT_UNDER_INTL_ACC_STA = Column(Numeric(20, 4), comment='国际会计准则净利润')
    COMP_TYPE_CODE = Column(VARCHAR(2), comment='公司类型代码')
    S_FA_EPS_BASIC = Column(Numeric(20, 4), comment='基本每股收益')
    S_FA_EPS_DILUTED = Column(Numeric(20, 4), comment='稀释每股收益')
    OTHER_INCOME = Column(Numeric(20, 4), comment='其他收益')
    MEMO = Column(VARCHAR(1000), comment='备注')
    CREDIT_IMPAIRMENT_LOSS = Column(Numeric(20, 4), comment='信用减值损失')
    NET_EXPOSURE_HEDGING_BENEFITS = Column(Numeric(20, 4), comment='净敞口套期收益')
    RD_EXPENSE = Column(Numeric(20, 4), comment='研发费用')
    STMNOTE_FINEXP = Column(Numeric(20, 4), comment='财务费用:利息费用')
    FIN_EXP_INT_INC = Column(Numeric(20, 4), comment='财务费用:利息收入')


class BSHAREIPO(Base):
    """中国B股首次公开发行数据"""
    __tablename__ = 'BSHAREIPO'
    OBJECT_ID = Column(VARCHAR(100), primary_key=True, comment='对象ID')
    S_INFO_WINDCODE = Column(VARCHAR(40), comment='Wind代码')
    CRNCY_CODE = Column(VARCHAR(10), comment='货币代码')
    S_IPO_PRICE = Column(Numeric(20, 4), comment='发行价格(元)')
    S_IPO_PRE_DILUTEDPE = Column(Numeric(20, 4), comment='发行市盈率(发行前股本)')
    S_IPO_DILUTEDPE = Column(Numeric(20, 4), comment='发行市盈率(发行后股本)')
    S_IPO_AMOUNT = Column(Numeric(20, 4), comment='发行数量(万股)')
    S_IPO_AMTBYPLACING = Column(Numeric(20, 4), comment='网上发行数量(万股)')
    S_IPO_AMTTOJUR = Column(Numeric(20, 4), comment='网下发行数量(万股)')
    S_IPO_COLLECTION = Column(Numeric(20, 4), comment='募集资金(万元)')
    S_IPO_CASHRATIO = Column(Numeric(20, 8), comment='网上发行中签率(%)')
    S_IPO_PURCHASECODE = Column(VARCHAR(10), comment='网上申购代码')
    S_IPO_SUBDATE = Column(VARCHAR(8), comment='申购日')
    S_IPO_JURISDATE = Column(VARCHAR(8), comment='向一般法人配售上市日期')
    S_IPO_INSTISDATE = Column(VARCHAR(8), comment='向战略投资者配售部分上市日期')
    S_IPO_EXPECTLISTDATE = Column(VARCHAR(8), comment='预计上市日期')
    S_IPO_FUNDVERIFICATIONDATE = Column(VARCHAR(8), comment='申购资金验资日')
    S_IPO_RATIODATE = Column(VARCHAR(8), comment='中签率公布日')
    S_FELLOW_UNFROZEDATE = Column(VARCHAR(8), comment='申购资金解冻日')
    S_IPO_LISTDATE = Column(VARCHAR(8), comment='上市日')
    S_IPO_PUBOFFRDATE = Column(VARCHAR(8), comment='招股公告日')
    S_IPO_ANNCEDATE = Column(VARCHAR(8), comment='发行公告日')
    S_IPO_ANNCELSTDATE = Column(VARCHAR(8), comment='上市公告日')
    S_IPO_ROADSHOWSTARTDATE = Column(VARCHAR(8), comment='初步询价(预路演)起始日期')
    S_IPO_ROADSHOWENDDATE = Column(VARCHAR(8), comment='初步询价(预路演)终止日期')
    S_IPO_PLACINGDATE = Column(VARCHAR(8), comment='网下配售发行公告日')
    S_IPO_APPLYSTARTDATE = Column(VARCHAR(8), comment='网下申购起始日期')
    S_IPO_APPLYENDDATE = Column(VARCHAR(8), comment='网下申购截止日期')
    S_IPO_PRICEANNOUNCEDATE = Column(VARCHAR(8), comment='网下定价公告日')
    S_IPO_PLACINGRESULTDATE = Column(VARCHAR(8), comment='网下配售结果公告日')
    S_IPO_FUNDENDDATE = Column(VARCHAR(8), comment='网下申购资金到帐截止日')
    S_IPO_CAPVERIFICATIONDATE = Column(VARCHAR(8), comment='网下验资日')
    S_IPO_REFUNDDATE = Column(VARCHAR(8), comment='网下多余款项退还日')
    S_IPO_EXPECTEDCOLLECTION = Column(Numeric(20, 4), comment='预计募集资金(万元)')
    S_IPO_LIST_FEE = Column(Numeric(20, 4), comment='发行费用(万元)')
    S_IPO_NAMEBYPLACING = Column(VARCHAR(20), comment='上网发行简称')
    S_IPO_SHOWPRICEDOWNLIMIT = Column(Numeric(20, 4), comment='投标询价申购价格下限')
    S_IPO_PAR = Column(Numeric(24, 8), comment='面值')
    S_IPO_PURCHASEUPLIMIT = Column(Numeric(20, 4), comment='申购上限(个人)')
    S_IPO_NEW_FACEVALUE = Column(Numeric(24, 8), comment='最新每股面值')


class BSHAREIPOAMOUNT(Base):
    """中国B股股票发行数量"""
    __tablename__ = 'BSHAREIPOAMOUNT'
    OBJECT_ID = Column(VARCHAR(38), primary_key=True, comment='对象ID')
    S_INFO_WINDCODE = Column(VARCHAR(40), comment='Wind代码')
    CHANGE_DATE = Column(VARCHAR(8), comment='变动日')
    ANN_DATE = Column(VARCHAR(8), comment='公告日')
    S_IPO_OSDEXPOFFAMOUNT = Column(Numeric(20, 4), comment='发行股份数')
    S_SHARE_TOTALRESTRICTED = Column(Numeric(20, 4), comment='限售股数')
    S_SHARE_TOTALTRADABLE = Column(Numeric(20, 4), comment='无限售股份数')
    S_SHARE_BE_LISTED = Column(Numeric(20, 4), comment='其中:待上市流通股数')
    S_SHARE_NTRD_STATJUR = Column(Numeric(20, 4), comment='非流通股份数')
    S_SHARE_CHANGEREASON = Column(VARCHAR(100), comment='[内部]股本变动原因')


class BSHAREIPOZL(Base):
    """中国B股首次公开发行数据(增量)"""
    __tablename__ = 'BSHAREIPOZL'
    OBJECT_ID = Column(VARCHAR(100), primary_key=True, comment='对象ID')
    S_INFO_WINDCODE = Column(VARCHAR(40), comment='Wind代码')
    CRNCY_CODE = Column(VARCHAR(10), comment='货币代码')
    S_IPO_PRICE = Column(Numeric(20, 4), comment='发行价格(元)')
    S_IPO_PRE_DILUTEDPE = Column(Numeric(20, 4), comment='发行市盈率(发行前股本)')
    S_IPO_DILUTEDPE = Column(Numeric(20, 4), comment='发行市盈率(发行后股本)')
    S_IPO_AMOUNT = Column(Numeric(20, 4), comment='发行数量(万股)')
    S_IPO_AMTBYPLACING = Column(Numeric(20, 4), comment='网上发行数量(万股)')
    S_IPO_AMTTOJUR = Column(Numeric(20, 4), comment='网下发行数量(万股)')
    S_IPO_COLLECTION = Column(Numeric(20, 4), comment='募集资金(万元)')
    S_IPO_CASHRATIO = Column(Numeric(20, 8), comment='网上发行中签率(%)')
    S_IPO_PURCHASECODE = Column(VARCHAR(10), comment='网上申购代码')
    S_IPO_SUBDATE = Column(VARCHAR(8), comment='申购日')
    S_IPO_JURISDATE = Column(VARCHAR(8), comment='向一般法人配售上市日期')
    S_IPO_INSTISDATE = Column(VARCHAR(8), comment='向战略投资者配售部分上市日期')
    S_IPO_EXPECTLISTDATE = Column(VARCHAR(8), comment='预计上市日期')
    S_IPO_FUNDVERIFICATIONDATE = Column(VARCHAR(8), comment='申购资金验资日')
    S_IPO_RATIODATE = Column(VARCHAR(8), comment='中签率公布日')
    S_FELLOW_UNFROZEDATE = Column(VARCHAR(8), comment='申购资金解冻日')
    S_IPO_LISTDATE = Column(VARCHAR(8), comment='上市日')
    S_IPO_PUBOFFRDATE = Column(VARCHAR(8), comment='招股公告日')
    S_IPO_ANNCEDATE = Column(VARCHAR(8), comment='发行公告日')
    S_IPO_ANNCELSTDATE = Column(VARCHAR(8), comment='上市公告日')
    S_IPO_ROADSHOWSTARTDATE = Column(VARCHAR(8), comment='初步询价(预路演)起始日期')
    S_IPO_ROADSHOWENDDATE = Column(VARCHAR(8), comment='初步询价(预路演)终止日期')
    S_IPO_PLACINGDATE = Column(VARCHAR(8), comment='网下配售发行公告日')
    S_IPO_APPLYSTARTDATE = Column(VARCHAR(8), comment='网下申购起始日期')
    S_IPO_APPLYENDDATE = Column(VARCHAR(8), comment='网下申购截止日期')
    S_IPO_PRICEANNOUNCEDATE = Column(VARCHAR(8), comment='网下定价公告日')
    S_IPO_PLACINGRESULTDATE = Column(VARCHAR(8), comment='网下配售结果公告日')
    S_IPO_FUNDENDDATE = Column(VARCHAR(8), comment='网下申购资金到帐截止日')
    S_IPO_CAPVERIFICATIONDATE = Column(VARCHAR(8), comment='网下验资日')
    S_IPO_REFUNDDATE = Column(VARCHAR(8), comment='网下多余款项退还日')
    S_IPO_EXPECTEDCOLLECTION = Column(Numeric(20, 4), comment='预计募集资金(万元)')
    S_IPO_LIST_FEE = Column(Numeric(20, 4), comment='发行费用(万元)')
    S_IPO_NAMEBYPLACING = Column(VARCHAR(20), comment='上网发行简称')
    S_IPO_SHOWPRICEDOWNLIMIT = Column(Numeric(20, 4), comment='投标询价申购价格下限')
    S_IPO_PAR = Column(Numeric(5, 0), comment='面值')
    S_IPO_PURCHASEUPLIMIT = Column(Numeric(20, 4), comment='申购上限(个人)')


class BSHAREISSUINGDATEPREDICT(Base):
    """中国B股定期报告披露日期"""
    __tablename__ = 'BSHAREISSUINGDATEPREDICT'
    OBJECT_ID = Column(VARCHAR(100), primary_key=True, comment='对象ID')
    S_INFO_WINDCODE = Column(VARCHAR(40), comment='Wind代码')
    REPORT_PERIOD = Column(VARCHAR(8), comment='报告期')
    S_STM_PREDICT_ISSUINGDATE = Column(VARCHAR(8), comment='预计披露日期')
    S_STM_ACTUAL_ISSUINGDATE = Column(VARCHAR(8), comment='实际披露日期')


class BSHAREMAJOREVENT(Base):
    """中国B股重大事件汇总"""
    __tablename__ = 'BSHAREMAJOREVENT'
    OBJECT_ID = Column(VARCHAR(100), primary_key=True, comment='对象ID')
    S_INFO_WINDCODE = Column(VARCHAR(40), comment='Wind代码')
    S_EVENT_CATEGORYCODE = Column(Numeric(9, 0), comment='事件类型代码')
    S_EVENT_ANNCEDATE = Column(VARCHAR(8), comment='披露日期')
    S_EVENT_HAPDATE = Column(VARCHAR(8), comment='发生日期')
    S_EVENT_EXPDATE = Column(VARCHAR(8), comment='失效日期')
    S_EVENT_CONTENT = Column(VARCHAR, comment='事件内容')
    S_EVENT_TEMPLATEID = Column(Numeric(12, 0), comment='模板ID')
    SEC_ID = Column(VARCHAR(10), comment='证券ID')


class BSHARENEINDUSTRIESCLASS(Base):
    """中国B股国民经济行业分类"""
    __tablename__ = 'BSHARENEINDUSTRIESCLASS'
    OBJECT_ID = Column(VARCHAR(100), primary_key=True, comment='对象ID')
    S_INFO_WINDCODE = Column(VARCHAR(40), comment='Wind代码')
    NE_IND_CODE = Column(VARCHAR(50), comment='国民经济行业代码')
    ENTRY_DT = Column(VARCHAR(8), comment='纳入日期')
    REMOVE_DT = Column(VARCHAR(8), comment='剔除日期')
    CUR_SIGN = Column(VARCHAR(10), comment='最新标志')


class BSHAREPREVIOUSNAME(Base):
    """中国B股证券曾用名"""
    __tablename__ = 'BSHAREPREVIOUSNAME'
    OBJECT_ID = Column(VARCHAR(100), primary_key=True, comment='对象ID')
    S_INFO_WINDCODE = Column(VARCHAR(40), comment='Wind代码')
    BEGINDATE = Column(VARCHAR(8), comment='起始日期')
    ENDDATE = Column(VARCHAR(8), comment='截止日期')
    ANN_DT = Column(VARCHAR(8), comment='公告日期')
    S_INFO_NAME = Column(VARCHAR(40), comment='证券简称')
    CHANGEREASON = Column(Numeric(9, 0), comment='变动原因代码')


class BSHAREPREVIOUSNAMEZL(Base):
    """中国B股证券曾用名(增量)"""
    __tablename__ = 'BSHAREPREVIOUSNAMEZL'
    OBJECT_ID = Column(VARCHAR(100), primary_key=True, comment='对象ID')
    S_INFO_WINDCODE = Column(VARCHAR(40), comment='Wind代码')
    BEGINDATE = Column(VARCHAR(8), comment='起始日期')
    ENDDATE = Column(VARCHAR(8), comment='截止日期')
    ANN_DT = Column(VARCHAR(8), comment='公告日期')
    S_INFO_NAME = Column(VARCHAR(40), comment='证券简称')
    CHANGEREASON = Column(Numeric(9, 0), comment='变动原因代码')


class BSHAREPROFITEXPRESS(Base):
    """中国B股业绩快报"""
    __tablename__ = 'BSHAREPROFITEXPRESS'
    OBJECT_ID = Column(VARCHAR(100), primary_key=True, comment='对象ID')
    S_INFO_WINDCODE = Column(VARCHAR(40), comment='Wind代码')
    ANN_DT = Column(VARCHAR(8), comment='公告日期')
    REPORT_PERIOD = Column(VARCHAR(8), comment='报告期')
    OPER_REV = Column(Numeric(20, 4), comment='营业收入(元)')
    OPER_PROFIT = Column(Numeric(20, 4), comment='营业利润(元)')
    TOT_PROFIT = Column(Numeric(20, 4), comment='利润总额(元)')
    NET_PROFIT_EXCL_MIN_INT_INC = Column(Numeric(20, 4), comment='净利润(元)')
    TOT_ASSETS = Column(Numeric(20, 4), comment='总资产(元)')
    TOT_SHRHLDR_EQY_EXCL_MIN_INT = Column(Numeric(20, 4), comment='股东权益合计(不含少数股东权益)(元)')
    EPS_DILUTED = Column(Numeric(20, 4), comment='每股收益(摊薄)(元)')
    ROE_DILUTED = Column(Numeric(20, 4), comment='净资产收益率(摊薄)(%)')
    S_ISAUDIT = Column(Numeric(5, 0), comment='是否审计')


class BSHAREPROSECUTION(Base):
    """中国B股诉讼事件"""
    __tablename__ = 'BSHAREPROSECUTION'
    OBJECT_ID = Column(VARCHAR(100), primary_key=True, comment='对象ID')
    S_INFO_WINDCODE = Column(VARCHAR(40), comment='Wind代码')
    S_INFO_COMPCODE = Column(VARCHAR(40), comment='公司ID')
    ANN_DT = Column(VARCHAR(8), comment='公告日期')
    TITLE = Column(VARCHAR(40), comment='案件名称')
    ACCUSER = Column(VARCHAR(3000), comment='原告方')
    DEFENDANT = Column(VARCHAR(3000), comment='被告方')
    PRO_TYPE = Column(VARCHAR(10), comment='诉讼类型')
    AMOUNT = Column(Numeric(20, 4), comment='涉案金额')
    CRNCY_CODE = Column(VARCHAR(10), comment='货币代码')
    PROSECUTE_DT = Column(VARCHAR(8), comment='起诉日期')
    COURT = Column(VARCHAR(200), comment='一审受理法院')
    JUDGE_DT = Column(VARCHAR(8), comment='判决日期')
    RESULT = Column(VARCHAR, comment='判决内容')
    IS_APPEAL = Column(Numeric(5, 0), comment='是否上诉')
    APPELLANT = Column(VARCHAR(1), comment='二审上诉方(是否原告)')
    COURT2 = Column(VARCHAR(200), comment='二审受理法院')
    JUDGE_DT2 = Column(VARCHAR(8), comment='二审判决日期')
    RESULT2 = Column(VARCHAR(2000), comment='二审判决内容')
    RESULTAMOUNT = Column(Numeric(20, 4), comment='判决金额')
    BRIEFRESULT = Column(VARCHAR(100), comment='诉讼结果')
    EXECUTION = Column(VARCHAR, comment='执行情况')
    INTRODUCTION = Column(VARCHAR, comment='案件描述')
    LITIGATION_EVENTS_ID = Column(VARCHAR(40), comment='诉讼事件ID')


class BSHARERIGHTISSUE(Base):
    """中国B股配股"""
    __tablename__ = 'BSHARERIGHTISSUE'
    OBJECT_ID = Column(VARCHAR(100), primary_key=True, comment='对象ID')
    S_INFO_WINDCODE = Column(VARCHAR(40), comment='Wind代码')
    S_RIGHTSISSUE_PROGRESS = Column(VARCHAR(10), comment='方案进度')
    S_RIGHTSISSUE_PRICE = Column(Numeric(20, 4), comment='配股价格(元)')
    S_RIGHTSISSUE_RATIO = Column(Numeric(20, 4), comment='配股比例')
    S_RIGHTSISSUE_AMOUNT = Column(Numeric(20, 4), comment='配股计划数量(万股)')
    S_RIGHTSISSUE_AMOUNTACT = Column(Numeric(20, 4), comment='配股实际数量(万股)')
    S_RIGHTSISSUE_NETCOLLECTION = Column(Numeric(20, 4), comment='募集资金(元)')
    S_RIGHTSISSUE_REGDATESHAREB = Column(VARCHAR(8), comment='股权登记日')
    S_RIGHTSISSUE_EXDIVIDENDDATE = Column(VARCHAR(8), comment='除权日')
    S_RIGHTSISSUE_LISTEDDATE = Column(VARCHAR(8), comment='配股上市日')
    S_RIGHTSISSUE_PAYSTARTDATE = Column(VARCHAR(8), comment='缴款起始日')
    S_RIGHTSISSUE_PAYENDDATE = Column(VARCHAR(8), comment='缴款终止日')
    S_RIGHTSISSUE_PREPLANDATE = Column(VARCHAR(8), comment='预案公告日')
    S_RIGHTSISSUE_SMTGANNCEDATE = Column(VARCHAR(8), comment='股东大会公告日')
    S_RIGHTSISSUE_PASSDATE = Column(VARCHAR(8), comment='发审委通过公告日')
    S_RIGHTSISSUE_APPROVEDDATE = Column(VARCHAR(8), comment='证监会核准公告日')
    S_RIGHTSISSUE_ANNCEDATE = Column(VARCHAR(8), comment='配股实施公告日')
    S_RIGHTSISSUE_RESULTDATE = Column(VARCHAR(8), comment='配股结果公告日')
    S_RIGHTSISSUE_LISTANNDATE = Column(VARCHAR(8), comment='上市公告日')
    S_RIGHTSISSUE_GUARANTOR = Column(VARCHAR(8), comment='基准年度')
    S_RIGHTSISSUE_GUARTYPE = Column(Numeric(20, 4), comment='基准股本(万股)')
    S_RIGHTSISSUE_CODE = Column(VARCHAR(10), comment='配售代码')
    ANN_DT = Column(VARCHAR(8), comment='最新公告日期')
    S_RIGHTSISSUE_YEAR = Column(VARCHAR(8), comment='配股年度')
    S_RIGHTSISSUE_CONTENT = Column(VARCHAR(150), comment='配股说明')


class BSHARESECNINDUSTRIESCLASS(Base):
    """中国B股证监会新版行业分类"""
    __tablename__ = 'BSHARESECNINDUSTRIESCLASS'
    OBJECT_ID = Column(VARCHAR(100), primary_key=True, comment='对象ID')
    S_INFO_WINDCODE = Column(VARCHAR(40), comment='Wind代码')
    SEC_IND_CODE = Column(VARCHAR(50), comment='证监会行业代码')
    ENTRY_DT = Column(VARCHAR(8), comment='纳入日期')
    REMOVE_DT = Column(VARCHAR(8), comment='剔除日期')
    CUR_SIGN = Column(VARCHAR(10), comment='最新标志')


class BSHARESEO(Base):
    """中国B股增发"""
    __tablename__ = 'BSHARESEO'
    OBJECT_ID = Column(VARCHAR(100), primary_key=True, comment='对象ID')
    S_INFO_WINDCODE = Column(VARCHAR(40), comment='Wind代码')
    S_FELLOW_PROGRESS = Column(VARCHAR(10), comment='方案进度')
    S_FELLOW_ISSUETYPE = Column(VARCHAR(10), comment='发行方式')
    CRNCY_CODE = Column(VARCHAR(10), comment='货币代码')
    S_FELLOW_PRICE = Column(Numeric(20, 4), comment='发行价格(元)')
    S_FELLOW_AMOUNT = Column(Numeric(20, 4), comment='发行数量(万股)')
    S_FELLOW_COLLECTION = Column(Numeric(20, 4), comment='募集资金(元)')
    S_FELLOW_RECORDDATE = Column(VARCHAR(8), comment='股权登记日')
    S_FELLOW_PAYSTARTDATE = Column(VARCHAR(8), comment='向老股东配售(或优先配售)缴款起始日')
    S_FELLOW_PAYENDDATE = Column(VARCHAR(8), comment='向老股东配售(或优先配售)缴款终止日')
    S_FELLOW_SUBDATE = Column(VARCHAR(8), comment='网上申购日')
    S_FELLOW_OTCDATE = Column(VARCHAR(8), comment='向网下(定向)增发日期')
    S_FELLOW_LISTDATE = Column(VARCHAR(8), comment='向公众增发股份上市日期')
    S_FELLOW_INSTLISTDATE = Column(VARCHAR(8), comment='向机构增发股份上市日期')
    S_FELLOW_CHANGEDATE = Column(VARCHAR(8), comment='定向增发股份变动日期')
    S_FELLOW_ROADSHOWDATE = Column(VARCHAR(8), comment='网上路演日')
    S_FELLOW_REFUNDDATE = Column(VARCHAR(8), comment='网下申购资金(定金)退款日')
    S_FELLOW_UNFROZEDATE = Column(VARCHAR(8), comment='网上申购资金解冻日')
    S_FELLOW_PREPLANDATE = Column(VARCHAR(8), comment='预案公告日')
    S_FELLOW_SMTGANNCEDATE = Column(VARCHAR(8), comment='股东大会公告日')
    S_FELLOW_PASSDATE = Column(VARCHAR(8), comment='发审委通过公告日')
    S_FELLOW_APPROVEDDATE = Column(VARCHAR(8), comment='证监会核准公告日')
    S_FELLOW_ANNCEDATE = Column(VARCHAR(8), comment='上网发行公告日')
    S_FELLOW_RATIOANNCEDATE = Column(VARCHAR(8), comment='网上中签率公告日')
    S_FELLOW_OFFERINGDATE = Column(VARCHAR(8), comment='增发公告日')
    S_FELLOW_LISTANNDATE = Column(VARCHAR(8), comment='上市公告日')
    S_FELLOW_OFFERINGOBJECT = Column(VARCHAR(200), comment='发行对象')
    S_FELLOW_PRICEUPLIMIT = Column(Numeric(20, 4), comment='增发预案价上限')
    S_FELLOW_PRICEDOWNLIMIT = Column(Numeric(20, 4), comment='增发预案价下限')
    S_SEO_CODE = Column(VARCHAR(10), comment='增发代码')
    S_SEO_NAME = Column(VARCHAR(20), comment='增发简称')
    S_SEO_PE = Column(Numeric(20, 4), comment='发行市盈率(摊薄)')
    S_SEO_AMTBYPLACING = Column(Numeric(20, 4), comment='上网发行数量(万股)')
    S_SEO_AMTTOJUR = Column(Numeric(20, 4), comment='网下发行数量(万股)')


class BSHAREST(Base):
    """中国B股特别处理"""
    __tablename__ = 'BSHAREST'
    OBJECT_ID = Column(VARCHAR(100), primary_key=True, comment='对象ID')
    S_INFO_WINDCODE = Column(VARCHAR(40), comment='Wind代码')
    S_TYPE_ST = Column(VARCHAR(8), comment='特别处理类型')
    ENTRY_DT = Column(VARCHAR(8), comment='实施日期')
    REMOVE_DT = Column(VARCHAR(8), comment='撤销日期')


class BSHARESTOCKREPO(Base):
    """中国B股回购"""
    __tablename__ = 'BSHARESTOCKREPO'
    OBJECT_ID = Column(VARCHAR(100), primary_key=True, comment='对象ID')
    S_INFO_WINDCODE = Column(VARCHAR(40), comment='Wind代码')
    EVENT_ID = Column(VARCHAR(38), comment='事件ID')
    ANN_DT = Column(VARCHAR(8), comment='公告日期')
    END_DT = Column(VARCHAR(8), comment='截止日期')
    STATUS = Column(Numeric(9, 0), comment='进度类型代码')
    EXP_DT = Column(VARCHAR(8), comment='过期日期')
    QTY = Column(Numeric(20, 4), comment='回购数量')
    AMT = Column(Numeric(20, 4), comment='回购金额')
    S_DQ_HIGH = Column(Numeric(20, 4), comment='最高价')
    S_DQ_LOW = Column(Numeric(20, 4), comment='最低价')
    CRNCY_CODE = Column(VARCHAR(20), comment='货币代码')
    STOCK_REPO_OBJECTIVE_CODE = Column(Numeric(9, 0), comment='股份回购目的代码')
    S_SHARE_LSTTYPECODE = Column(Numeric(9, 0), comment='回购股份类型代码')
    TOTAL_SHARE_RATIO = Column(Numeric(20, 4), comment='回购股数占总股本比例')
    REPURCHASE_FUNDS_RATIO = Column(Numeric(20, 4), comment='占预计回购资金比例')
    REPURCHASE_SHARES_RATIO = Column(Numeric(20, 4), comment='占预计回购股份比例')
    EXP_QTY = Column(Numeric(20, 4), comment='预计回购股份总数')


class BSHARESTRANGETRADEDETAIL(Base):
    """中国B股交易异动"""
    __tablename__ = 'BSHARESTRANGETRADEDETAIL'
    OBJECT_ID = Column(VARCHAR(100), primary_key=True, comment='对象ID')
    S_INFO_WINDCODE = Column(VARCHAR(40), comment='Wind代码')
    TYPE_CODE = Column(VARCHAR(3), comment='异动类型')
    START_DT = Column(VARCHAR(8), comment='起始日')
    END_DT = Column(VARCHAR(8), comment='截止日')
    VOLUME = Column(Numeric(20, 4), comment='成交量(万股)')
    AMOUNT = Column(Numeric(20, 4), comment='成交金额(元)')
    PCTCHANGE = Column(Numeric(20, 4), comment='涨跌幅(%)')
    CHANGE_DEVIATION = Column(Numeric(20, 4), comment='涨跌幅偏离值(%)')
    SWING = Column(Numeric(20, 4), comment='振幅(%)')
    TURN = Column(Numeric(20, 4), comment='换手率(%)')
    CHANGE_DEVIATION_3D = Column(Numeric(20, 4), comment='连续三个交易日累计涨跌幅偏离值(%)')
    TURN_3D = Column(Numeric(20, 4), comment='连续三个交易日累计换手率(%)')
    TURN_3DTO5D = Column(Numeric(20, 4), comment='连续三个交易日日均换手率与前五个交易日的日均换手率的比值(倍)')
    MARGIN_PCT = Column(Numeric(20, 4), comment='融资买入(融资卖出)成交占比')


class BSHARETRADINGSUSPENSION(Base):
    """中国B股停复牌信息"""
    __tablename__ = 'BSHARETRADINGSUSPENSION'
    OBJECT_ID = Column(VARCHAR(100), primary_key=True, comment='对象ID')
    S_INFO_WINDCODE = Column(VARCHAR(40), comment='Wind代码')
    S_DQ_SUSPENDDATE = Column(VARCHAR(8), comment='停牌日期')
    S_DQ_SUSPENDTYPE = Column(Numeric(9, 0), comment='停牌类型代码')
    S_DQ_RESUMPDATE = Column(VARCHAR(8), comment='复牌日期')
    S_DQ_CHANGEREASON = Column(VARCHAR(400), comment='停牌原因')
    S_DQ_TIME = Column(VARCHAR(200), comment='停复牌时间')
    S_DQ_CHANGEREASONTYPE = Column(Numeric(9, 0), comment='停牌原因代码')
